au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif
syntax on
syntax enable
set showcmd
set ruler           " Show line and column number
set relativenumber  " left column displays relative numbers lines
set number          " now with current line number instead of 0
set laststatus=2    " Always display the status line
set autoread        " Read open files when changed in the background
set autowrite		" Automatically save before commands like :next and :make
set ignorecase		" Do case insensitive matching
set smartcase       " Unless we type a capital
set smartcase		" Do smart case matching
set incsearch		" Incremental search
set hlsearch        " Highlight searches
set tabstop=4       " Tab = 4 spaces
set shiftwidth=4
set expandtab       " Insert spaces instead of tabs
set splitright
set foldmethod=indent
set foldnestmax=10
set nofoldenable
set foldlevel=2
set cursorline
autocmd WinEnter * setlocal cursorline
autocmd WinLeave * setlocal nocursorline
set wildmenu        " Enhanced command completion
set hidden		    " Hide buffers when they are abandoned
set showmatch		" Show matching bracket
set mouse=a		    " Enable mouse usage (all modes)
set history=200     " Keep 200 lines of command history
set ttimeoutlen=5   " Time to wait for a key sequence to complete. Keep low.
set ffs=unix,dos
set encoding=UTF-8
set exrc
set secure

let c_gnu = 1
let c_space_errors = 1
let c_curly_error = 1
let c_ansi_typedefs = 1
let c_ansi_constants = 1
let mapleader = ","

" Disable arrow movement, resize splits instead.
nnoremap <Down>  :resize +2<CR>
nnoremap <Up>    :resize -2<CR>
nnoremap <Left>  :vertical resize +2<CR>
nnoremap <Right> :vertical resize -2<CR>

" Moves a line up/down
no <S-Down> ddp
no <S-Up> ddkP

" NERDtree shortcut
nnoremap <C-n> :NERDTreeToggle<CR>

" tagbar shortcut
nnoremap <F8> :TagbarToggle<CR>

" autoclosing brackets
inoremap (<CR> (<CR>)<Esc>O
inoremap {<CR> {<CR>}<Esc>O
inoremap {; {<CR>};<Esc>O
inoremap {, {<CR>},<Esc>O
inoremap [<CR> [<CR>]<Esc>O
inoremap [; [<CR>];<Esc>O
inoremap [, [<CR>],<Esc>O

" copy to system clipboard using ,c
xnoremap <leader>c "+y
no <leader>s :sp 
no <leader>v :vsp 

" switch buffers using ,b
nnoremap <leader>b :b <C-d>
