" load pathogen
execute pathogen#infect()

source ~/.vim/startup/settings.vim
source ~/.vim/startup/plugins.vim
source ~/.vim/startup/statusline.vim
" source ~/.vim/startup/startscreen.vim
source ~/.vim/startup/mappings.vim
