#!/bin/bash
# aliases
alias ls='ls -h --color=auto --group-directories-first'
alias ll='ls -alF --group-directories-first'
alias la='ls -A'
alias l='ls -CF'
alias dir='dir --color=auto'
alias vdir='vdir --color=auto'
alias grep='grep -n -I --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'
alias cp='cp -i'
alias df='df -h'
alias du='du -h'
alias mv='mv -i'
alias less='less -r' # raw control characters
alias whence='type -a' # where, of a sort
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias py='python3'
alias python='python3'
alias doc="cd ~/Documenti"
alias dl="cd ~/Scaricati"
alias h="cd ~"
alias gits="git status"
alias unixtime="date +%s"
alias bc="bc -q"
alias gdb="gdb -q"
alias gcc-asm="gcc -std=c17 -S -Wall -Wextra -masm=intel -fno-asynchronous-unwind-tables"
alias g++-asm="g++ -std=c++20 -S -Wall -Wextra -masm=intel -fno-asynchronous-unwind-tables -fno-exceptions -fno-rtti"
# add an "alert" alias for long running commands.  Use like so: sleep 10; alert
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'
alias easyrpg="easyrpg-player --window"
if command -v xdg-open &> /dev/null; then
    alias open="xdg-open"
fi
alias ip="ip -c"

# os-specific aliases
if [[ $(expr substr $(uname -s) 1 5) == "Linux" ]]; then
    alias youtube-dl="youtube-dl -o '%(title)s.%(ext)s'"
    alias mp3-dl="yt-dlp -x --audio-format mp3 --audio-quality 0 -o '%(title)s.%(ext)s'"
    alias ogg-dl="yt-dlp -x --audio-format vorbis --audio-quality 0 -o '%(title)s.%(ext)s'"
    alias pl-dl="yt-dlp -x --audio-format vorbis --audio-quality 0 -o '%(playlist_index)s. %(title)s.%(ext)s'"
elif [[ $(expr substr $(uname -s) 1 4) == "MSYS" ]]; then
    alias winhome="cd /c/Users/chri"
    alias winprog="cd /c/Users/chri/Principale/programming"
elif [[ $(expr substr $(uname -s) 1 5) == "MINGW" ]]; then 
    alias winhome="cd /c/Users/chri"
    alias winprog="cd /c/Users/chri/Principale/programming"
fi
