#!/bin/bash

# for inserting sprite to "nonsense" hack
function insspr {
    pushd . > /dev/null
    cd ~/cnd/Hacks/Nonsense
    wine cmd < insertspr.bat
    popd > /dev/null
}

# functions for outputting text in the prompt.
# using "echo" is a hack.
function ps1_ssh {
    if [[ "${SSH_CLIENT}" || "${SSH_TTY}" ]]; then
        printf " $(ip route get 1 | tr -s ' ' | cut -d' ' -f7) "
    fi
}

function ps1_read_only {
    if [ ! -w "$PWD" ]; then
        printf ' '
    fi
}

function ps1_git {
    local branch=$(git rev-parse --abbrev-ref HEAD 2> /dev/null)
    if [ -n "$branch" ]; then
        if [ -n "$(git status --porcelain 2> /dev/null)" ]; then
            printf '\033[1;33m'
        else
            printf '\033[1;32m'
        fi
        printf "$branch "
    fi
}

