" Name:         Gruvbox 8
" Description:  Retro groove color scheme originally designed by morhetz
" Author:       morhetz <morhetz@gmail.com>
" Maintainer:   Lifepillar <lifepillar@lifepillar.me>
" Website:      https://github.com/lifepillar/vim-gruvbox8/
" License:      Vim License (see `:help license`)
" Last Updated: Sat Jun  5 17:06:38 2021

" Generated by Colortemplate v2.1.0

hi clear
let g:colors_name = 'gruvbox8'

let s:t_Co = exists('&t_Co') && !empty(&t_Co) && &t_Co > 1 ? &t_Co : 2
let s:italics = (&t_ZH != '' && &t_ZH != '[7m') || has('gui_running') || has('nvim')

let s:italics = s:italics && get(g:, 'gruvbox_italics', 1)
hi! link CursorColumn CursorLine
hi! link QuickFixLine Search
hi! link StatusLineTerm StatusLine
hi! link StatusLineTermNC StatusLineNC
hi! link VisualNOS Visual
hi! link Tag Special
hi! link lCursor Cursor
hi! link iCursor Cursor
hi! link vCursor Cursor

if s:t_Co >= 256
  if &background ==# 'dark'
    hi Terminal ctermfg=187 ctermbg=235 cterm=NONE
    if get(g:, 'gruvbox_transp_bg', 0)
      hi Normal ctermfg=187 ctermbg=NONE cterm=NONE
      hi CursorLineNr ctermfg=214 ctermbg=NONE cterm=NONE
      hi FoldColumn ctermfg=102 ctermbg=NONE cterm=NONE
      hi SignColumn ctermfg=187 ctermbg=NONE cterm=NONE
      hi VertSplit ctermfg=59 ctermbg=NONE cterm=NONE
    else
      hi Normal ctermfg=187 ctermbg=235 cterm=NONE
      hi CursorLineNr ctermfg=214 ctermbg=237 cterm=NONE
      hi FoldColumn ctermfg=102 ctermbg=237 cterm=NONE
      hi SignColumn ctermfg=187 ctermbg=237 cterm=NONE
      hi VertSplit ctermfg=59 ctermbg=235 cterm=NONE
    endif
    hi ColorColumn ctermfg=NONE ctermbg=237 cterm=NONE
    hi Comment ctermfg=102 ctermbg=NONE cterm=italic
    hi CursorLine ctermfg=NONE ctermbg=237 cterm=NONE
    hi Error ctermfg=203 ctermbg=235 cterm=reverse
    hi ErrorMsg ctermfg=235 ctermbg=203
    "cterm=bold
    hi Folded ctermfg=102 ctermbg=237 cterm=italic
    hi LineNr ctermfg=243 ctermbg=NONE cterm=NONE
    hi MatchParen ctermfg=NONE ctermbg=239 cterm=bold,underline
    hi NonText ctermfg=239 ctermbg=NONE cterm=NONE
    hi Pmenu ctermfg=187 ctermbg=239 cterm=NONE
    hi PmenuSbar ctermfg=NONE ctermbg=239 cterm=NONE
    hi PmenuSel ctermfg=235 ctermbg=109
    hi PmenuThumb ctermfg=NONE ctermbg=243 cterm=NONE
    hi SpecialKey ctermfg=102 ctermbg=NONE cterm=NONE
    hi StatusLine ctermfg=239 ctermbg=187 cterm=reverse
    hi StatusLineNC ctermfg=237 ctermbg=137 cterm=reverse
    hi TabLine ctermfg=243 ctermbg=237 cterm=NONE
    hi TabLineFill ctermfg=243 ctermbg=237 cterm=NONE
    hi TabLineSel ctermfg=142 ctermbg=237 cterm=NONE
    hi ToolbarButton ctermfg=230 ctermbg=59 cterm=bold
    hi ToolbarLine ctermfg=NONE ctermbg=59 cterm=NONE
    hi Visual ctermfg=NONE ctermbg=59 cterm=NONE
    hi WildMenu ctermfg=109 ctermbg=239 cterm=bold
    hi Conceal ctermfg=109 ctermbg=NONE cterm=NONE
    hi Cursor ctermfg=NONE ctermbg=NONE cterm=reverse
    hi DiffAdd ctermfg=142 ctermbg=235 cterm=reverse
    hi DiffChange ctermfg=107 ctermbg=235 cterm=reverse
    hi DiffDelete ctermfg=203 ctermbg=235 cterm=reverse
    hi DiffText ctermfg=214 ctermbg=235 cterm=reverse
    hi Directory ctermfg=142 ctermbg=NONE cterm=bold
    hi EndOfBuffer ctermfg=235 ctermbg=NONE cterm=NONE
    hi IncSearch ctermfg=208 ctermbg=235 cterm=reverse
    hi ModeMsg ctermfg=214 ctermbg=NONE cterm=bold
    hi MoreMsg ctermfg=214 ctermbg=NONE cterm=bold
    hi Question ctermfg=208 ctermbg=NONE cterm=bold
    hi Search ctermfg=214 ctermbg=235 cterm=reverse
    hi SpellBad ctermfg=203 ctermbg=NONE cterm=italic,underline
    hi SpellCap ctermfg=109 ctermbg=NONE cterm=italic,underline
    hi SpellLocal ctermfg=107 ctermbg=NONE cterm=italic,underline
    hi SpellRare ctermfg=175 ctermbg=NONE cterm=italic,underline
    hi Title ctermfg=142 ctermbg=NONE cterm=bold
    hi WarningMsg ctermfg=203 ctermbg=NONE cterm=bold
    hi Boolean ctermfg=175 ctermbg=NONE cterm=NONE
    hi Character ctermfg=175 ctermbg=NONE cterm=NONE
    hi Conditional ctermfg=203 ctermbg=NONE cterm=NONE
    hi Constant ctermfg=175 ctermbg=NONE cterm=NONE
    hi Define ctermfg=107 ctermbg=NONE cterm=NONE
    hi Debug ctermfg=203 ctermbg=NONE cterm=NONE
    hi Delimiter ctermfg=208 ctermbg=NONE cterm=NONE
    hi Error ctermfg=203 ctermbg=235 cterm=reverse
    "cterm=bold,reverse
    hi Exception ctermfg=203 ctermbg=NONE cterm=NONE
    hi Float ctermfg=175 ctermbg=NONE cterm=NONE
    hi Function ctermfg=142 ctermbg=NONE
    hi Identifier ctermfg=109 ctermbg=NONE cterm=NONE
    hi Ignore ctermfg=fg ctermbg=NONE cterm=NONE
    hi Include ctermfg=107 ctermbg=NONE cterm=NONE
    hi Keyword ctermfg=203 ctermbg=NONE cterm=NONE
    hi Label ctermfg=203 ctermbg=NONE cterm=NONE
    hi Macro ctermfg=107 ctermbg=NONE cterm=NONE
    hi Number ctermfg=175 ctermbg=NONE cterm=NONE
    hi Operator ctermfg=107 ctermbg=NONE cterm=NONE
    hi PreCondit ctermfg=107 ctermbg=NONE cterm=NONE
    hi PreProc ctermfg=107 ctermbg=NONE cterm=NONE
    hi Repeat ctermfg=203 ctermbg=NONE cterm=NONE
    hi SpecialChar ctermfg=203 ctermbg=NONE cterm=NONE
    hi SpecialComment ctermfg=203 ctermbg=NONE cterm=NONE
    hi Statement ctermfg=203 ctermbg=NONE cterm=NONE
    hi StorageClass ctermfg=208 ctermbg=NONE cterm=NONE
    hi Special ctermfg=208 ctermbg=NONE cterm=italic
    hi String ctermfg=142 ctermbg=NONE cterm=italic
    hi Structure ctermfg=107 ctermbg=NONE cterm=NONE
    hi Todo ctermfg=fg ctermbg=235 cterm=bold,italic
    hi Type ctermfg=214 ctermbg=NONE cterm=NONE
    hi Typedef ctermfg=214 ctermbg=NONE cterm=NONE
    hi Underlined ctermfg=109 ctermbg=NONE cterm=underline
    hi CursorIM ctermfg=NONE ctermbg=NONE cterm=reverse
    if !s:italics
      hi Comment cterm=NONE
      hi Folded cterm=NONE
      hi SpellBad cterm=underline
      hi SpellCap cterm=underline
      hi SpellLocal cterm=underline
      hi SpellRare cterm=underline
      hi Special cterm=NONE
      hi String cterm=NONE
      hi Todo cterm=bold
    endif
    if !get(g:, 'gruvbox_italicize_strings', 1)
      hi Special gui=NONE cterm=NONE
      hi String gui=NONE cterm=NONE
    endif
    hi NormalMode ctermfg=137 ctermbg=235 cterm=reverse
    hi InsertMode ctermfg=109 ctermbg=235 cterm=reverse
    hi ReplaceMode ctermfg=107 ctermbg=235 cterm=reverse
    hi VisualMode ctermfg=208 ctermbg=235 cterm=reverse
    hi CommandMode ctermfg=175 ctermbg=235 cterm=reverse
    hi Warnings ctermfg=208 ctermbg=235 cterm=reverse
    hi User1 ctermfg=203 ctermbg=239
    hi User2 ctermfg=107 ctermbg=239 cterm=bold
    hi User3 ctermfg=109 ctermbg=239 cterm=bold
    hi User4 ctermfg=235 ctermbg=243

    if !(get(g:, 'gruvbox_plugin_hi_groups', 0) || get(g:, 'gruvbox_filetype_hi_groups', 0))
      finish
    endif
    if get(g:, "gruvbox_plugin_hi_groups", 0)
      hi ALEError ctermfg=NONE ctermbg=NONE cterm=underline
      hi ALEWarning ctermfg=NONE ctermbg=NONE cterm=underline
      hi ALEInfo ctermfg=NONE ctermbg=NONE cterm=underline
      hi ALEErrorSign ctermfg=203 ctermbg=237 cterm=NONE
      hi ALEWarningSign ctermfg=214 ctermbg=237 cterm=NONE
      hi ALEInfoSign ctermfg=109 ctermbg=237 cterm=NONE
      hi BufTabLineCurrent ctermfg=235 ctermbg=137 cterm=NONE
      hi BufTabLineActive ctermfg=137 ctermbg=239 cterm=NONE
      hi BufTabLineHidden ctermfg=243 ctermbg=237 cterm=NONE
      hi BufTabLineFill ctermfg=235 ctermbg=235 cterm=NONE
      hi CocErrorSign ctermfg=203 ctermbg=237 cterm=NONE
      hi CocWarningSign ctermfg=208 ctermbg=237 cterm=NONE
      hi CocInfoSign ctermfg=214 ctermbg=237 cterm=NONE
      hi CocHintSign ctermfg=109 ctermbg=237 cterm=NONE
      hi CocErrorFloat ctermfg=203 ctermbg=NONE cterm=NONE
      hi CocWarningFloat ctermfg=208 ctermbg=NONE cterm=NONE
      hi CocInfoFloat ctermfg=214 ctermbg=NONE cterm=NONE
      hi CocHintFloat ctermfg=109 ctermbg=NONE cterm=NONE
      hi CtrlPMatch ctermfg=214 ctermbg=NONE cterm=NONE
      hi CtrlPNoEntries ctermfg=203 ctermbg=NONE cterm=NONE
      hi CtrlPPrtBase ctermfg=239 ctermbg=NONE cterm=NONE
      hi CtrlPPrtCursor ctermfg=109 ctermbg=NONE cterm=NONE
      hi CtrlPLinePre ctermfg=239 ctermbg=NONE cterm=NONE
      hi CtrlPMode1 ctermfg=109 ctermbg=239 cterm=bold
      hi CtrlPMode2 ctermfg=235 ctermbg=109 cterm=bold
      hi CtrlPStats ctermfg=137 ctermbg=239 cterm=bold
      hi DirvishPathTail ctermfg=107 ctermbg=NONE cterm=NONE
      hi DirvishArg ctermfg=214 ctermbg=NONE cterm=NONE
      hi! link EasyMotionTarget Search
      hi! link EasyMotionShade Comment
      hi gitcommitSelectedFile ctermfg=142 ctermbg=NONE cterm=NONE
      hi gitcommitDiscardedFile ctermfg=203 ctermbg=NONE cterm=NONE
      if get(g:, 'gruvbox_transp_bg', 0)
        hi GitGutterAdd ctermfg=142 ctermbg=NONE cterm=NONE
        hi GitGutterChange ctermfg=107 ctermbg=NONE cterm=NONE
        hi GitGutterDelete ctermfg=203 ctermbg=NONE cterm=NONE
        hi GitGutterChangeDelete ctermfg=107 ctermbg=NONE cterm=NONE
      else
        hi GitGutterAdd ctermfg=142 ctermbg=237 cterm=NONE
        hi GitGutterChange ctermfg=107 ctermbg=237 cterm=NONE
        hi GitGutterDelete ctermfg=203 ctermbg=237 cterm=NONE
        hi GitGutterChangeDelete ctermfg=107 ctermbg=237 cterm=NONE
      endif
      if get(g:, 'indent_guides_auto_colors', 0)
        if get(g:, 'gruvbox_invert_indent_guides', 0)
          hi IndentGuidesOdd ctermfg=235 ctermbg=239 cterm=reverse
          hi IndentGuidesEven ctermfg=235 ctermbg=237 cterm=reverse
        else
          hi IndentGuidesOdd ctermfg=235 ctermbg=239 cterm=NONE
          hi IndentGuidesEven ctermfg=235 ctermbg=237 cterm=NONE
        endif
      endif
      if !exists('g:indentLine_color_term')
        let g:indentLine_color_term = 239
      endif
      if !exists('g:indentLine_color_gui')
        let g:indentLine_color_gui = '#504945'
      endif
      hi LspDiagnosticsDefaultError ctermfg=203 ctermbg=NONE cterm=NONE
      hi LspDiagnosticsSignError ctermfg=203 ctermbg=237 cterm=NONE
      hi LspDiagnosticsUnderlineError ctermfg=NONE ctermbg=NONE cterm=NONE
      hi LspDiagnosticsDefaultWarning ctermfg=208 ctermbg=NONE cterm=NONE
      hi LspDiagnosticsSignWarning ctermfg=208 ctermbg=237 cterm=NONE
      hi LspDiagnosticsUnderlineWarning ctermfg=NONE ctermbg=NONE cterm=NONE
      hi LspDiagnosticsDefaultInformation ctermfg=214 ctermbg=NONE cterm=NONE
      hi LspDiagnosticsSignInformation ctermfg=214 ctermbg=237 cterm=NONE
      hi LspDiagnosticsUnderlineInformation ctermfg=NONE ctermbg=NONE cterm=NONE
      hi LspDiagnosticsDefaultHint ctermfg=109 ctermbg=NONE cterm=NONE
      hi LspDiagnosticsSignHint ctermfg=109 ctermbg=237 cterm=NONE
      hi LspDiagnosticsUnderlineHint ctermfg=NONE ctermbg=NONE cterm=NONE
      hi LanguageClientError ctermfg=203 ctermbg=NONE cterm=NONE
      hi LanguageClientErrorSign ctermfg=203 ctermbg=235 cterm=NONE
      hi LanguageClientWarning ctermfg=214 ctermbg=NONE cterm=NONE
      hi LanguageClientWarningSign ctermfg=214 ctermbg=237 cterm=NONE
      hi LangaugeClientInfo ctermfg=109 ctermbg=NONE cterm=NONE
      hi LanguageClientInfoSign ctermfg=109 ctermbg=237 cterm=NONE
      hi LanguageClientCodeLens ctermfg=109 ctermbg=NONE cterm=NONE
      hi NERDTreeDir ctermfg=107 ctermbg=NONE cterm=NONE
      hi NERDTreeDirSlash ctermfg=107 ctermbg=NONE cterm=NONE
      hi NERDTreeOpenable ctermfg=208 ctermbg=NONE cterm=NONE
      hi NERDTreeClosable ctermfg=208 ctermbg=NONE cterm=NONE
      hi NERDTreeFile ctermfg=187 ctermbg=NONE cterm=NONE
      hi NERDTreeExecFile ctermfg=214 ctermbg=NONE cterm=NONE
      hi NERDTreeUp ctermfg=102 ctermbg=NONE cterm=NONE
      hi NERDTreeCWD ctermfg=142 ctermbg=NONE cterm=NONE
      hi NERDTreeHelp ctermfg=187 ctermbg=NONE cterm=NONE
      hi NERDTreeToggleOn ctermfg=142 ctermbg=NONE cterm=NONE
      hi NERDTreeToggleOff ctermfg=203 ctermbg=NONE cterm=NONE
      hi netrwDir ctermfg=107 ctermbg=NONE cterm=NONE
      hi netrwClassify ctermfg=107 ctermbg=NONE cterm=NONE
      hi netrwLink ctermfg=102 ctermbg=NONE cterm=NONE
      hi netrwSymLink ctermfg=187 ctermbg=NONE cterm=NONE
      hi netrwExe ctermfg=214 ctermbg=NONE cterm=NONE
      hi netrwComment ctermfg=102 ctermbg=NONE cterm=NONE
      hi netrwList ctermfg=109 ctermbg=NONE cterm=NONE
      hi netrwHelpCmd ctermfg=107 ctermbg=NONE cterm=NONE
      hi netrwCmdSep ctermfg=144 ctermbg=NONE cterm=NONE
      hi netrwVersion ctermfg=142 ctermbg=NONE cterm=NONE
      " Rainbow Parentheses
      if !exists('g:rbpt_colorpairs')
        let g:rbpt_colorpairs = [['blue', '#458588'], ['magenta', '#b16286'],
              \ ['red', '#cc241d'], ['166', '#d65d0e']]
      endif

      let g:rainbow_guifgs = [ '#d65d0e', '#cc241d', '#b16286', '#458588' ]
      let g:rainbow_ctermfgs = [ '166', 'red', 'magenta', 'blue' ]

      if !exists('g:rainbow_conf')
        let g:rainbow_conf = {}
      endif
      if !has_key(g:rainbow_conf, 'guifgs')
        let g:rainbow_conf['guifgs'] = g:rainbow_guifgs
      endif
      if !has_key(g:rainbow_conf, 'ctermfgs')
        let g:rainbow_conf['ctermfgs'] = g:rainbow_ctermfgs
      endif

      let g:niji_dark_colours = g:rbpt_colorpairs
      let g:niji_light_colours = g:rbpt_colorpairs
      hi ShowMarksHLl ctermfg=109 ctermbg=237 cterm=NONE
      hi ShowMarksHLu ctermfg=109 ctermbg=237 cterm=NONE
      hi ShowMarksHLo ctermfg=109 ctermbg=237 cterm=NONE
      hi ShowMarksHLm ctermfg=109 ctermbg=237 cterm=NONE
      hi SignifySignAdd ctermfg=142 ctermbg=237 cterm=NONE
      hi SignifySignChange ctermfg=107 ctermbg=237 cterm=NONE
      hi SignifySignDelete ctermfg=203 ctermbg=237 cterm=NONE
      hi SignatureMarkText ctermfg=109 ctermbg=237 cterm=NONE
      hi SignatureMarkerText ctermfg=175 ctermbg=237 cterm=NONE
      hi StartifyBracket ctermfg=144 ctermbg=NONE cterm=NONE
      hi StartifyFile ctermfg=187 ctermbg=NONE cterm=NONE
      hi StartifyNumber ctermfg=109 ctermbg=NONE cterm=NONE
      hi StartifyPath ctermfg=102 ctermbg=NONE cterm=NONE
      hi StartifySlash ctermfg=102 ctermbg=NONE cterm=NONE
      hi StartifySection ctermfg=214 ctermbg=NONE cterm=NONE
      hi StartifySpecial ctermfg=239 ctermbg=NONE cterm=NONE
      hi StartifyHeader ctermfg=208 ctermbg=NONE cterm=NONE
      hi StartifyFooter ctermfg=239 ctermbg=NONE cterm=NONE
      hi SyntasticError ctermfg=NONE ctermbg=NONE cterm=underline
      hi SyntasticWarning ctermfg=NONE ctermbg=NONE cterm=underline
      hi SyntasticErrorSign ctermfg=203 ctermbg=237 cterm=NONE
      hi SyntasticWarningSign ctermfg=214 ctermbg=237 cterm=NONE
      hi multiple_cursors_cursor ctermfg=NONE ctermbg=NONE cterm=reverse
      hi multiple_cursors_visual ctermfg=NONE ctermbg=239 cterm=NONE
      let g:vimshell_escape_colors = [
            \ '#7c6f64', '#fb4934', '#b8bb26', '#fabd2f',
            \ '#83a598', '#d3869b', '#8ec07c', '#a89984',
            \ '#282828', '#fb4934', '#b8bb26', '#fe8019',
            \ '#83a598', '#d3869b', '#8ec07c', '#fbf1c7'
            \ ]
    endif
    if get(g:, "gruvbox_filetype_hi_groups", 0)
      hi diffAdded ctermfg=142 ctermbg=NONE cterm=NONE
      hi diffRemoved ctermfg=203 ctermbg=NONE cterm=NONE
      hi diffChanged ctermfg=107 ctermbg=NONE cterm=NONE
      hi diffFile ctermfg=208 ctermbg=NONE cterm=NONE
      hi diffNewFile ctermfg=214 ctermbg=NONE cterm=NONE
      hi diffLine ctermfg=109 ctermbg=NONE cterm=NONE
      hi htmlTag ctermfg=109 ctermbg=NONE cterm=NONE
      hi htmlEndTag ctermfg=109 ctermbg=NONE cterm=NONE
      hi htmlTagName ctermfg=107 ctermbg=NONE cterm=bold
      hi htmlArg ctermfg=107 ctermbg=NONE cterm=NONE
      hi htmlScriptTag ctermfg=175 ctermbg=NONE cterm=NONE
      hi htmlTagN ctermfg=187 ctermbg=NONE cterm=NONE
      hi htmlSpecialTagName ctermfg=107 ctermbg=NONE cterm=bold
      hi htmlLink ctermfg=137 ctermbg=NONE cterm=underline
      hi htmlSpecialChar ctermfg=208 ctermbg=NONE cterm=NONE
      hi htmlBold ctermfg=fg ctermbg=235 cterm=bold
      hi htmlBoldUnderline ctermfg=fg ctermbg=235 cterm=bold,underline
      hi htmlBoldItalic ctermfg=fg ctermbg=235 cterm=bold,italic
      hi htmlBoldUnderlineItalic ctermfg=fg ctermbg=235 cterm=bold,italic,underline
      hi htmlUnderline ctermfg=fg ctermbg=235 cterm=underline
      hi htmlUnderlineItalic ctermfg=fg ctermbg=235 cterm=italic,underline
      hi htmlItalic ctermfg=fg ctermbg=235 cterm=italic
      hi xmlTag ctermfg=109 ctermbg=NONE cterm=NONE
      hi xmlEndTag ctermfg=109 ctermbg=NONE cterm=NONE
      hi xmlTagName ctermfg=109 ctermbg=NONE cterm=NONE
      hi xmlEqual ctermfg=109 ctermbg=NONE cterm=NONE
      hi docbkKeyword ctermfg=107 ctermbg=NONE cterm=bold
      hi xmlDocTypeDecl ctermfg=102 ctermbg=NONE cterm=NONE
      hi xmlDocTypeKeyword ctermfg=175 ctermbg=NONE cterm=NONE
      hi xmlCdataStart ctermfg=102 ctermbg=NONE cterm=NONE
      hi xmlCdataCdata ctermfg=175 ctermbg=NONE cterm=NONE
      hi dtdFunction ctermfg=102 ctermbg=NONE cterm=NONE
      hi dtdTagName ctermfg=175 ctermbg=NONE cterm=NONE
      hi xmlAttrib ctermfg=107 ctermbg=NONE cterm=NONE
      hi xmlProcessingDelim ctermfg=102 ctermbg=NONE cterm=NONE
      hi dtdParamEntityPunct ctermfg=102 ctermbg=NONE cterm=NONE
      hi dtdParamEntityDPunct ctermfg=102 ctermbg=NONE cterm=NONE
      hi xmlAttribPunct ctermfg=102 ctermbg=NONE cterm=NONE
      hi xmlEntity ctermfg=208 ctermbg=NONE cterm=NONE
      hi xmlEntityPunct ctermfg=208 ctermbg=NONE cterm=NONE
      hi vimCommentTitle ctermfg=137 ctermbg=NONE cterm=bold
      hi vimNotation ctermfg=208 ctermbg=NONE cterm=NONE
      hi vimBracket ctermfg=208 ctermbg=NONE cterm=NONE
      hi vimMapModKey ctermfg=208 ctermbg=NONE cterm=NONE
      hi vimFuncSID ctermfg=144 ctermbg=NONE cterm=NONE
      hi vimSetSep ctermfg=144 ctermbg=NONE cterm=NONE
      hi vimSep ctermfg=144 ctermbg=NONE cterm=NONE
      hi vimContinue ctermfg=144 ctermbg=NONE cterm=NONE
      hi clojureKeyword ctermfg=109 ctermbg=NONE cterm=NONE
      hi clojureCond ctermfg=208 ctermbg=NONE cterm=NONE
      hi clojureSpecial ctermfg=208 ctermbg=NONE cterm=NONE
      hi clojureDefine ctermfg=208 ctermbg=NONE cterm=NONE
      hi clojureFunc ctermfg=214 ctermbg=NONE cterm=NONE
      hi clojureRepeat ctermfg=214 ctermbg=NONE cterm=NONE
      hi clojureCharacter ctermfg=107 ctermbg=NONE cterm=NONE
      hi clojureStringEscape ctermfg=107 ctermbg=NONE cterm=NONE
      hi clojureException ctermfg=203 ctermbg=NONE cterm=NONE
      hi clojureRegexp ctermfg=107 ctermbg=NONE cterm=NONE
      hi clojureRegexpEscape ctermfg=107 ctermbg=NONE cterm=NONE
      hi clojureRegexpCharClass ctermfg=144 ctermbg=NONE cterm=bold
      hi! link clojureRegexpMod clojureRegexpCharClass
      hi! link clojureRegexpQuantifier clojureRegexpCharClass
      hi clojureParen ctermfg=144 ctermbg=NONE cterm=NONE
      hi clojureAnonArg ctermfg=214 ctermbg=NONE cterm=NONE
      hi clojureVariable ctermfg=109 ctermbg=NONE cterm=NONE
      hi clojureMacro ctermfg=208 ctermbg=NONE cterm=NONE
      hi clojureMeta ctermfg=214 ctermbg=NONE cterm=NONE
      hi clojureDeref ctermfg=214 ctermbg=NONE cterm=NONE
      hi clojureQuote ctermfg=214 ctermbg=NONE cterm=NONE
      hi clojureUnquote ctermfg=214 ctermbg=NONE cterm=NONE
      hi cOperator ctermfg=175 ctermbg=NONE cterm=NONE
      hi cStructure ctermfg=208 ctermbg=NONE cterm=NONE
      hi pythonBuiltin ctermfg=208 ctermbg=NONE cterm=NONE
      hi pythonBuiltinObj ctermfg=208 ctermbg=NONE cterm=NONE
      hi pythonBuiltinFunc ctermfg=208 ctermbg=NONE cterm=NONE
      hi pythonFunction ctermfg=107 ctermbg=NONE cterm=NONE
      hi pythonDecorator ctermfg=203 ctermbg=NONE cterm=NONE
      hi pythonInclude ctermfg=109 ctermbg=NONE cterm=NONE
      hi pythonImport ctermfg=109 ctermbg=NONE cterm=NONE
      hi pythonRun ctermfg=109 ctermbg=NONE cterm=NONE
      hi pythonCoding ctermfg=109 ctermbg=NONE cterm=NONE
      hi pythonOperator ctermfg=203 ctermbg=NONE cterm=NONE
      hi pythonException ctermfg=203 ctermbg=NONE cterm=NONE
      hi pythonExceptions ctermfg=175 ctermbg=NONE cterm=NONE
      hi pythonBoolean ctermfg=175 ctermbg=NONE cterm=NONE
      hi pythonDot ctermfg=144 ctermbg=NONE cterm=NONE
      hi pythonConditional ctermfg=203 ctermbg=NONE cterm=NONE
      hi pythonRepeat ctermfg=203 ctermbg=NONE cterm=NONE
      hi pythonDottedName ctermfg=142 ctermbg=NONE cterm=bold
      hi cssBraces ctermfg=109 ctermbg=NONE cterm=NONE
      hi cssFunctionName ctermfg=214 ctermbg=NONE cterm=NONE
      hi cssIdentifier ctermfg=208 ctermbg=NONE cterm=NONE
      hi cssClassName ctermfg=142 ctermbg=NONE cterm=NONE
      hi cssColor ctermfg=109 ctermbg=NONE cterm=NONE
      hi cssSelectorOp ctermfg=109 ctermbg=NONE cterm=NONE
      hi cssSelectorOp2 ctermfg=109 ctermbg=NONE cterm=NONE
      hi cssImportant ctermfg=142 ctermbg=NONE cterm=NONE
      hi cssVendor ctermfg=187 ctermbg=NONE cterm=NONE
      hi cssTextProp ctermfg=107 ctermbg=NONE cterm=NONE
      hi cssAnimationProp ctermfg=107 ctermbg=NONE cterm=NONE
      hi cssUIProp ctermfg=214 ctermbg=NONE cterm=NONE
      hi cssTransformProp ctermfg=107 ctermbg=NONE cterm=NONE
      hi cssTransitionProp ctermfg=107 ctermbg=NONE cterm=NONE
      hi cssPrintProp ctermfg=107 ctermbg=NONE cterm=NONE
      hi cssPositioningProp ctermfg=214 ctermbg=NONE cterm=NONE
      hi cssBoxProp ctermfg=107 ctermbg=NONE cterm=NONE
      hi cssFontDescriptorProp ctermfg=107 ctermbg=NONE cterm=NONE
      hi cssFlexibleBoxProp ctermfg=107 ctermbg=NONE cterm=NONE
      hi cssBorderOutlineProp ctermfg=107 ctermbg=NONE cterm=NONE
      hi cssBackgroundProp ctermfg=107 ctermbg=NONE cterm=NONE
      hi cssMarginProp ctermfg=107 ctermbg=NONE cterm=NONE
      hi cssListProp ctermfg=107 ctermbg=NONE cterm=NONE
      hi cssTableProp ctermfg=107 ctermbg=NONE cterm=NONE
      hi cssFontProp ctermfg=107 ctermbg=NONE cterm=NONE
      hi cssPaddingProp ctermfg=107 ctermbg=NONE cterm=NONE
      hi cssDimensionProp ctermfg=107 ctermbg=NONE cterm=NONE
      hi cssRenderProp ctermfg=107 ctermbg=NONE cterm=NONE
      hi cssColorProp ctermfg=107 ctermbg=NONE cterm=NONE
      hi cssGeneratedContentProp ctermfg=107 ctermbg=NONE cterm=NONE
      hi javaScriptBraces ctermfg=187 ctermbg=NONE cterm=NONE
      hi javaScriptFunction ctermfg=107 ctermbg=NONE cterm=NONE
      hi javaScriptIdentifier ctermfg=203 ctermbg=NONE cterm=NONE
      hi javaScriptMember ctermfg=109 ctermbg=NONE cterm=NONE
      hi javaScriptNumber ctermfg=175 ctermbg=NONE cterm=NONE
      hi javaScriptNull ctermfg=175 ctermbg=NONE cterm=NONE
      hi javaScriptParens ctermfg=144 ctermbg=NONE cterm=NONE
      hi javascriptImport ctermfg=107 ctermbg=NONE cterm=NONE
      hi javascriptExport ctermfg=107 ctermbg=NONE cterm=NONE
      hi javascriptClassKeyword ctermfg=107 ctermbg=NONE cterm=NONE
      hi javascriptClassExtends ctermfg=107 ctermbg=NONE cterm=NONE
      hi javascriptDefault ctermfg=107 ctermbg=NONE cterm=NONE
      hi javascriptClassName ctermfg=214 ctermbg=NONE cterm=NONE
      hi javascriptClassSuperName ctermfg=214 ctermbg=NONE cterm=NONE
      hi javascriptGlobal ctermfg=214 ctermbg=NONE cterm=NONE
      hi javascriptEndColons ctermfg=187 ctermbg=NONE cterm=NONE
      hi javascriptFuncArg ctermfg=187 ctermbg=NONE cterm=NONE
      hi javascriptGlobalMethod ctermfg=187 ctermbg=NONE cterm=NONE
      hi javascriptNodeGlobal ctermfg=187 ctermbg=NONE cterm=NONE
      hi javascriptBOMWindowProp ctermfg=187 ctermbg=NONE cterm=NONE
      hi javascriptArrayMethod ctermfg=187 ctermbg=NONE cterm=NONE
      hi javascriptArrayStaticMethod ctermfg=187 ctermbg=NONE cterm=NONE
      hi javascriptCacheMethod ctermfg=187 ctermbg=NONE cterm=NONE
      hi javascriptDateMethod ctermfg=187 ctermbg=NONE cterm=NONE
      hi javascriptMathStaticMethod ctermfg=187 ctermbg=NONE cterm=NONE
      hi javascriptURLUtilsProp ctermfg=187 ctermbg=NONE cterm=NONE
      hi javascriptBOMNavigatorProp ctermfg=187 ctermbg=NONE cterm=NONE
      hi javascriptDOMDocMethod ctermfg=187 ctermbg=NONE cterm=NONE
      hi javascriptDOMDocProp ctermfg=187 ctermbg=NONE cterm=NONE
      hi javascriptBOMLocationMethod ctermfg=187 ctermbg=NONE cterm=NONE
      hi javascriptBOMWindowMethod ctermfg=187 ctermbg=NONE cterm=NONE
      hi javascriptStringMethod ctermfg=187 ctermbg=NONE cterm=NONE
      hi javascriptVariable ctermfg=208 ctermbg=NONE cterm=NONE
      hi javascriptIdentifier ctermfg=208 ctermbg=NONE cterm=NONE
      hi javascriptClassSuper ctermfg=208 ctermbg=NONE cterm=NONE
      hi javascriptFuncKeyword ctermfg=107 ctermbg=NONE cterm=NONE
      hi javascriptAsyncFunc ctermfg=107 ctermbg=NONE cterm=NONE
      hi javascriptClassStatic ctermfg=208 ctermbg=NONE cterm=NONE
      hi javascriptOperator ctermfg=203 ctermbg=NONE cterm=NONE
      hi javascriptForOperator ctermfg=203 ctermbg=NONE cterm=NONE
      hi javascriptYield ctermfg=203 ctermbg=NONE cterm=NONE
      hi javascriptExceptions ctermfg=203 ctermbg=NONE cterm=NONE
      hi javascriptMessage ctermfg=203 ctermbg=NONE cterm=NONE
      hi javascriptTemplateSB ctermfg=107 ctermbg=NONE cterm=NONE
      hi javascriptTemplateSubstitution ctermfg=187 ctermbg=NONE cterm=NONE
      hi javascriptLabel ctermfg=187 ctermbg=NONE cterm=NONE
      hi javascriptObjectLabel ctermfg=187 ctermbg=NONE cterm=NONE
      hi javascriptPropertyName ctermfg=187 ctermbg=NONE cterm=NONE
      hi javascriptLogicSymbols ctermfg=187 ctermbg=NONE cterm=NONE
      hi javascriptArrowFunc ctermfg=214 ctermbg=NONE cterm=NONE
      hi javascriptDocParamName ctermfg=137 ctermbg=NONE cterm=NONE
      hi javascriptDocTags ctermfg=137 ctermbg=NONE cterm=NONE
      hi javascriptDocNotation ctermfg=137 ctermbg=NONE cterm=NONE
      hi javascriptDocParamType ctermfg=137 ctermbg=NONE cterm=NONE
      hi javascriptDocNamedParamType ctermfg=137 ctermbg=NONE cterm=NONE
      hi javascriptBrackets ctermfg=187 ctermbg=NONE cterm=NONE
      hi javascriptDOMElemAttrs ctermfg=187 ctermbg=NONE cterm=NONE
      hi javascriptDOMEventMethod ctermfg=187 ctermbg=NONE cterm=NONE
      hi javascriptDOMNodeMethod ctermfg=187 ctermbg=NONE cterm=NONE
      hi javascriptDOMStorageMethod ctermfg=187 ctermbg=NONE cterm=NONE
      hi javascriptHeadersMethod ctermfg=187 ctermbg=NONE cterm=NONE
      hi javascriptAsyncFuncKeyword ctermfg=203 ctermbg=NONE cterm=NONE
      hi javascriptAwaitFuncKeyword ctermfg=203 ctermbg=NONE cterm=NONE
      hi jsImport ctermfg=203 ctermbg=NONE cterm=NONE
      hi jsExport ctermfg=203 ctermbg=NONE cterm=NONE
      hi jsFrom ctermfg=203 ctermbg=NONE cterm=NONE
      hi jsThis ctermfg=175 ctermbg=NONE cterm=NONE
      hi jsParen ctermfg=109 ctermbg=NONE cterm=NONE
      hi jsOperator ctermfg=107 ctermbg=NONE cterm=NONE
      hi jsSpreadOperator ctermfg=142 ctermbg=NONE cterm=NONE
      hi jsSpreadExpression ctermfg=109 ctermbg=NONE cterm=NONE
      hi jsClassKeyword ctermfg=203 ctermbg=NONE cterm=NONE
      hi jsClassProperty ctermfg=142 ctermbg=NONE cterm=NONE
      hi jsExtendsKeyword ctermfg=203 ctermbg=NONE cterm=NONE
      hi jsExportDefault ctermfg=208 ctermbg=NONE cterm=bold
      hi jsTemplateBraces ctermfg=107 ctermbg=NONE cterm=NONE
      hi jsGlobalNodeObjects ctermfg=187 ctermbg=NONE cterm=NONE
      hi jsGlobalObjects ctermfg=187 ctermbg=NONE cterm=NONE
      hi jsFunction ctermfg=142 ctermbg=NONE cterm=NONE
      hi jsFuncParens ctermfg=175 ctermbg=NONE cterm=NONE
      hi jsFuncBlock ctermfg=109 ctermbg=NONE cterm=NONE
      hi jsParens ctermfg=144 ctermbg=NONE cterm=NONE
      hi jsNull ctermfg=175 ctermbg=NONE cterm=NONE
      hi jsUndefined ctermfg=175 ctermbg=NONE cterm=NONE
      hi jsClassDefinition ctermfg=214 ctermbg=NONE cterm=NONE
      hi jsFunctionKey ctermfg=142 ctermbg=NONE cterm=NONE
      hi jsBracket ctermfg=203 ctermbg=NONE cterm=NONE
      hi jsObjectColon ctermfg=203 ctermbg=NONE cterm=NONE
      hi jsObjectProp ctermfg=109 ctermbg=NONE cterm=NONE
      hi jsFuncBraces ctermfg=142 ctermbg=NONE cterm=NONE
      hi jsVariableDef ctermfg=214 ctermbg=NONE cterm=NONE
      hi jsObjectValue ctermfg=109 ctermbg=NONE cterm=NONE
      hi jsDestructuringBlock ctermfg=214 ctermbg=NONE cterm=NONE
      hi jsParenIfElse ctermfg=109 ctermbg=NONE cterm=NONE
      hi jsClassBlock ctermfg=109 ctermbg=NONE cterm=NONE
      hi jsFutureKeys ctermfg=208 ctermbg=NONE cterm=bold
      hi jsStorageClass ctermfg=208 ctermbg=NONE cterm=NONE
      hi jsModuleKeyword ctermfg=109 ctermbg=NONE cterm=NONE
      hi jsObjectShorthandProp ctermfg=109 ctermbg=NONE cterm=NONE
      hi jsxRegion ctermfg=109 ctermbg=NONE cterm=NONE
      hi jsxTagName ctermfg=109 ctermbg=NONE cterm=NONE
      hi jsxComponentName ctermfg=214 ctermbg=NONE cterm=NONE
      hi jsxEscapeJsAttributes ctermfg=109 ctermbg=NONE cterm=NONE
      hi jsxEscapeJsContent ctermfg=109 ctermbg=NONE cterm=NONE
      hi jsxAttrib ctermfg=214 ctermbg=NONE cterm=NONE
      hi jsxAttributeBraces ctermfg=187 ctermbg=NONE cterm=NONE
      hi jsxEqual ctermfg=107 ctermbg=NONE cterm=NONE
      hi jsxString ctermfg=142 ctermbg=NONE cterm=NONE
      hi jsxCloseTag ctermfg=109 ctermbg=NONE cterm=NONE
      hi jsxEndTag ctermfg=109 ctermbg=NONE cterm=NONE
      hi jsxEndString ctermfg=109 ctermbg=NONE cterm=NONE
      hi jsxCloseString ctermfg=109 ctermbg=NONE cterm=NONE
      hi jsxIfOperator ctermfg=107 ctermbg=NONE cterm=NONE
      hi jsxElseOperator ctermfg=107 ctermbg=NONE cterm=NONE
      hi jsxDot ctermfg=187 ctermbg=NONE cterm=NONE
      hi jsxNamespace ctermfg=109 ctermbg=NONE cterm=NONE
      hi jsxPunct ctermfg=107 ctermbg=NONE cterm=NONE
      hi typeScriptReserved ctermfg=107 ctermbg=NONE cterm=NONE
      hi typeScriptLabel ctermfg=107 ctermbg=NONE cterm=NONE
      hi typeScriptFuncKeyword ctermfg=107 ctermbg=NONE cterm=NONE
      hi typeScriptIdentifier ctermfg=208 ctermbg=NONE cterm=NONE
      hi typeScriptBraces ctermfg=187 ctermbg=NONE cterm=NONE
      hi typeScriptEndColons ctermfg=187 ctermbg=NONE cterm=NONE
      hi typeScriptDOMObjects ctermfg=187 ctermbg=NONE cterm=NONE
      hi typeScriptAjaxMethods ctermfg=187 ctermbg=NONE cterm=NONE
      hi typeScriptLogicSymbols ctermfg=187 ctermbg=NONE cterm=NONE
      hi! link typeScriptDocSeeTag Comment
      hi! link typeScriptDocParam Comment
      hi! link typeScriptDocTags vimCommentTitle
      hi typeScriptGlobalObjects ctermfg=187 ctermbg=NONE cterm=NONE
      hi typeScriptParens ctermfg=144 ctermbg=NONE cterm=NONE
      hi typeScriptOpSymbols ctermfg=144 ctermbg=NONE cterm=NONE
      hi typeScriptHtmlElemProperties ctermfg=187 ctermbg=NONE cterm=NONE
      hi typeScriptNull ctermfg=175 ctermbg=NONE cterm=NONE
      hi typeScriptInterpolationDelimiter ctermfg=107 ctermbg=NONE cterm=NONE
      hi purescriptModuleKeyword ctermfg=107 ctermbg=NONE cterm=NONE
      hi purescriptModuleName ctermfg=187 ctermbg=NONE cterm=NONE
      hi purescriptWhere ctermfg=107 ctermbg=NONE cterm=NONE
      hi purescriptDelimiter ctermfg=137 ctermbg=NONE cterm=NONE
      hi purescriptType ctermfg=187 ctermbg=NONE cterm=NONE
      hi purescriptImportKeyword ctermfg=107 ctermbg=NONE cterm=NONE
      hi purescriptHidingKeyword ctermfg=107 ctermbg=NONE cterm=NONE
      hi purescriptAsKeyword ctermfg=107 ctermbg=NONE cterm=NONE
      hi purescriptStructure ctermfg=107 ctermbg=NONE cterm=NONE
      hi purescriptOperator ctermfg=109 ctermbg=NONE cterm=NONE
      hi purescriptTypeVar ctermfg=187 ctermbg=NONE cterm=NONE
      hi purescriptConstructor ctermfg=187 ctermbg=NONE cterm=NONE
      hi purescriptFunction ctermfg=187 ctermbg=NONE cterm=NONE
      hi purescriptConditional ctermfg=208 ctermbg=NONE cterm=NONE
      hi purescriptBacktick ctermfg=208 ctermbg=NONE cterm=NONE
      hi coffeeExtendedOp ctermfg=144 ctermbg=NONE cterm=NONE
      hi coffeeSpecialOp ctermfg=144 ctermbg=NONE cterm=NONE
      hi coffeeCurly ctermfg=208 ctermbg=NONE cterm=NONE
      hi coffeeParen ctermfg=144 ctermbg=NONE cterm=NONE
      hi coffeeBracket ctermfg=208 ctermbg=NONE cterm=NONE
      hi rubyStringDelimiter ctermfg=142 ctermbg=NONE cterm=NONE
      hi rubyInterpolationDelimiter ctermfg=107 ctermbg=NONE cterm=NONE
      hi objcTypeModifier ctermfg=203 ctermbg=NONE cterm=NONE
      hi objcDirective ctermfg=109 ctermbg=NONE cterm=NONE
      hi goDirective ctermfg=107 ctermbg=NONE cterm=NONE
      hi goConstants ctermfg=175 ctermbg=NONE cterm=NONE
      hi goDeclaration ctermfg=203 ctermbg=NONE cterm=NONE
      hi goDeclType ctermfg=109 ctermbg=NONE cterm=NONE
      hi goBuiltins ctermfg=208 ctermbg=NONE cterm=NONE
      hi luaIn ctermfg=203 ctermbg=NONE cterm=NONE
      hi luaFunction ctermfg=107 ctermbg=NONE cterm=NONE
      hi luaTable ctermfg=208 ctermbg=NONE cterm=NONE
      hi moonSpecialOp ctermfg=144 ctermbg=NONE cterm=NONE
      hi moonExtendedOp ctermfg=144 ctermbg=NONE cterm=NONE
      hi moonFunction ctermfg=144 ctermbg=NONE cterm=NONE
      hi moonObject ctermfg=214 ctermbg=NONE cterm=NONE
      hi javaAnnotation ctermfg=109 ctermbg=NONE cterm=NONE
      hi javaDocTags ctermfg=107 ctermbg=NONE cterm=NONE
      hi! link javaCommentTitle vimCommentTitle
      hi javaParen ctermfg=144 ctermbg=NONE cterm=NONE
      hi javaParen1 ctermfg=144 ctermbg=NONE cterm=NONE
      hi javaParen2 ctermfg=144 ctermbg=NONE cterm=NONE
      hi javaParen3 ctermfg=144 ctermbg=NONE cterm=NONE
      hi javaParen4 ctermfg=144 ctermbg=NONE cterm=NONE
      hi javaParen5 ctermfg=144 ctermbg=NONE cterm=NONE
      hi javaOperator ctermfg=208 ctermbg=NONE cterm=NONE
      hi javaVarArg ctermfg=142 ctermbg=NONE cterm=NONE
      hi! link elixirDocString Comment
      hi elixirStringDelimiter ctermfg=142 ctermbg=NONE cterm=NONE
      hi elixirInterpolationDelimiter ctermfg=107 ctermbg=NONE cterm=NONE
      hi elixirModuleDeclaration ctermfg=214 ctermbg=NONE cterm=NONE
      hi scalaNameDefinition ctermfg=187 ctermbg=NONE cterm=NONE
      hi scalaCaseFollowing ctermfg=187 ctermbg=NONE cterm=NONE
      hi scalaCapitalWord ctermfg=187 ctermbg=NONE cterm=NONE
      hi scalaTypeExtension ctermfg=187 ctermbg=NONE cterm=NONE
      hi scalaKeyword ctermfg=203 ctermbg=NONE cterm=NONE
      hi scalaKeywordModifier ctermfg=203 ctermbg=NONE cterm=NONE
      hi scalaSpecial ctermfg=107 ctermbg=NONE cterm=NONE
      hi scalaOperator ctermfg=187 ctermbg=NONE cterm=NONE
      hi scalaTypeDeclaration ctermfg=214 ctermbg=NONE cterm=NONE
      hi scalaTypeTypePostDeclaration ctermfg=214 ctermbg=NONE cterm=NONE
      hi scalaInstanceDeclaration ctermfg=187 ctermbg=NONE cterm=NONE
      hi scalaInterpolation ctermfg=107 ctermbg=NONE cterm=NONE
      hi markdownItalic ctermfg=144 ctermbg=NONE cterm=italic
      hi markdownH1 ctermfg=142 ctermbg=NONE cterm=bold
      hi markdownH2 ctermfg=142 ctermbg=NONE cterm=bold
      hi markdownH3 ctermfg=214 ctermbg=NONE cterm=bold
      hi markdownH4 ctermfg=214 ctermbg=NONE cterm=bold
      hi markdownH5 ctermfg=214 ctermbg=NONE cterm=NONE
      hi markdownH6 ctermfg=214 ctermbg=NONE cterm=NONE
      hi markdownCode ctermfg=107 ctermbg=NONE cterm=NONE
      hi markdownCodeBlock ctermfg=107 ctermbg=NONE cterm=NONE
      hi markdownCodeDelimiter ctermfg=107 ctermbg=NONE cterm=NONE
      hi markdownBlockquote ctermfg=102 ctermbg=NONE cterm=NONE
      hi markdownListMarker ctermfg=102 ctermbg=NONE cterm=NONE
      hi markdownOrderedListMarker ctermfg=102 ctermbg=NONE cterm=NONE
      hi markdownRule ctermfg=102 ctermbg=NONE cterm=NONE
      hi markdownHeadingRule ctermfg=102 ctermbg=NONE cterm=NONE
      hi markdownUrlDelimiter ctermfg=144 ctermbg=NONE cterm=NONE
      hi markdownLinkDelimiter ctermfg=144 ctermbg=NONE cterm=NONE
      hi markdownLinkTextDelimiter ctermfg=144 ctermbg=NONE cterm=NONE
      hi markdownHeadingDelimiter ctermfg=208 ctermbg=NONE cterm=NONE
      hi markdownUrl ctermfg=175 ctermbg=NONE cterm=NONE
      hi markdownUrlTitleDelimiter ctermfg=142 ctermbg=NONE cterm=NONE
      hi markdownLinkText ctermfg=102 ctermbg=NONE cterm=underline
      hi! link markdownIdDeclaration markdownLinkText
      hi haskellType ctermfg=187 ctermbg=NONE cterm=NONE
      hi haskellIdentifier ctermfg=187 ctermbg=NONE cterm=NONE
      hi haskellSeparator ctermfg=187 ctermbg=NONE cterm=NONE
      hi haskellDelimiter ctermfg=137 ctermbg=NONE cterm=NONE
      hi haskellOperators ctermfg=109 ctermbg=NONE cterm=NONE
      hi haskellBacktick ctermfg=208 ctermbg=NONE cterm=NONE
      hi haskellStatement ctermfg=208 ctermbg=NONE cterm=NONE
      hi haskellConditional ctermfg=208 ctermbg=NONE cterm=NONE
      hi haskellLet ctermfg=107 ctermbg=NONE cterm=NONE
      hi haskellDefault ctermfg=107 ctermbg=NONE cterm=NONE
      hi haskellWhere ctermfg=107 ctermbg=NONE cterm=NONE
      hi haskellBottom ctermfg=107 ctermbg=NONE cterm=NONE
      hi haskellBlockKeywords ctermfg=107 ctermbg=NONE cterm=NONE
      hi haskellImportKeywords ctermfg=107 ctermbg=NONE cterm=NONE
      hi haskellDeclKeyword ctermfg=107 ctermbg=NONE cterm=NONE
      hi haskellDeriving ctermfg=107 ctermbg=NONE cterm=NONE
      hi haskellAssocType ctermfg=107 ctermbg=NONE cterm=NONE
      hi haskellNumber ctermfg=175 ctermbg=NONE cterm=NONE
      hi haskellPragma ctermfg=175 ctermbg=NONE cterm=NONE
      hi haskellString ctermfg=142 ctermbg=NONE cterm=NONE
      hi haskellChar ctermfg=142 ctermbg=NONE cterm=NONE
      hi jsonKeyword ctermfg=142 ctermbg=NONE cterm=NONE
      hi jsonQuote ctermfg=142 ctermbg=NONE cterm=NONE
      hi jsonBraces ctermfg=187 ctermbg=NONE cterm=NONE
      hi jsonString ctermfg=187 ctermbg=NONE cterm=NONE
      if !s:italics
        hi htmlBoldItalic cterm=bold
        hi htmlBoldUnderlineItalic cterm=bold,underline
        hi htmlUnderlineItalic cterm=underline
        hi htmlItalic cterm=NONE
        hi markdownItalic cterm=NONE
      endif
    endif
    unlet s:t_Co s:italics
    finish
  endif

  " Light background
  hi Terminal ctermfg=230 ctermbg=237 cterm=NONE
  if get(g:, 'gruvbox_transp_bg', 0)
    hi Normal ctermfg=237 ctermbg=NONE cterm=NONE
    hi CursorLineNr ctermfg=172 ctermbg=NONE cterm=NONE
    hi FoldColumn ctermfg=102 ctermbg=NONE cterm=NONE
    hi SignColumn ctermfg=237 ctermbg=NONE cterm=NONE
    hi VertSplit ctermfg=144 ctermbg=NONE cterm=NONE
  else
    hi Normal ctermfg=237 ctermbg=230 cterm=NONE
    hi CursorLineNr ctermfg=172 ctermbg=187 cterm=NONE
    hi FoldColumn ctermfg=102 ctermbg=187 cterm=NONE
    hi SignColumn ctermfg=237 ctermbg=187 cterm=NONE
    hi VertSplit ctermfg=144 ctermbg=230 cterm=NONE
  endif
  hi ColorColumn ctermfg=NONE ctermbg=187 cterm=NONE
  hi Comment ctermfg=102 ctermbg=NONE cterm=italic
  hi CursorLine ctermfg=NONE ctermbg=187 cterm=NONE
  hi Error ctermfg=124 ctermbg=230 cterm=bold,reverse
  hi ErrorMsg ctermfg=230 ctermbg=124 cterm=bold
  hi Folded ctermfg=102 ctermbg=187 cterm=italic
  hi LineNr ctermfg=137 ctermbg=NONE cterm=NONE
  hi MatchParen ctermfg=NONE ctermbg=187 cterm=bold,underline
  hi NonText ctermfg=187 ctermbg=NONE cterm=NONE
  hi Pmenu ctermfg=237 ctermbg=187 cterm=NONE
  hi PmenuSbar ctermfg=NONE ctermbg=187 cterm=NONE
  hi PmenuSel ctermfg=187 ctermbg=23
  hi PmenuThumb ctermfg=NONE ctermbg=137 cterm=NONE
  hi SpecialKey ctermfg=102 ctermbg=NONE cterm=NONE
  hi StatusLine ctermfg=187 ctermbg=237 cterm=reverse
  hi StatusLineNC ctermfg=187 ctermbg=243 cterm=reverse
  hi TabLine ctermfg=137 ctermbg=187 cterm=NONE
  hi TabLineFill ctermfg=137 ctermbg=187 cterm=NONE
  hi TabLineSel ctermfg=100 ctermbg=187 cterm=NONE
  hi ToolbarButton ctermfg=235 ctermbg=144 cterm=bold
  hi ToolbarLine ctermfg=NONE ctermbg=144 cterm=NONE
  hi Visual ctermfg=NONE ctermbg=144 cterm=NONE
  hi WildMenu ctermfg=23 ctermbg=187 cterm=bold
  hi Conceal ctermfg=23 ctermbg=NONE cterm=NONE
  hi Cursor ctermfg=NONE ctermbg=NONE cterm=reverse
  hi DiffAdd ctermfg=100 ctermbg=230 cterm=reverse
  hi DiffChange ctermfg=29 ctermbg=230 cterm=reverse
  hi DiffDelete ctermfg=124 ctermbg=230 cterm=reverse
  hi DiffText ctermfg=172 ctermbg=230 cterm=reverse
  hi Directory ctermfg=100 ctermbg=NONE cterm=bold
  hi EndOfBuffer ctermfg=230 ctermbg=NONE cterm=NONE
  hi IncSearch ctermfg=124 ctermbg=230 cterm=reverse
  hi ModeMsg ctermfg=172 ctermbg=NONE cterm=bold
  hi MoreMsg ctermfg=172 ctermbg=NONE cterm=bold
  hi Question ctermfg=124 ctermbg=NONE cterm=bold
  hi Search ctermfg=172 ctermbg=230 cterm=reverse
  hi SpellBad ctermfg=124 ctermbg=NONE cterm=italic,underline
  hi SpellCap ctermfg=23 ctermbg=NONE cterm=italic,underline
  hi SpellLocal ctermfg=29 ctermbg=NONE cterm=italic,underline
  hi SpellRare ctermfg=126 ctermbg=NONE cterm=italic,underline
  hi Title ctermfg=100 ctermbg=NONE cterm=bold
  hi WarningMsg ctermfg=124 ctermbg=NONE cterm=bold
  hi Boolean ctermfg=126 ctermbg=NONE cterm=NONE
  hi Character ctermfg=126 ctermbg=NONE cterm=NONE
  hi Conditional ctermfg=124 ctermbg=NONE cterm=NONE
  hi Constant ctermfg=126 ctermbg=NONE cterm=NONE
  hi Define ctermfg=29 ctermbg=NONE cterm=NONE
  hi Debug ctermfg=124 ctermbg=NONE cterm=NONE
  hi Delimiter ctermfg=124 ctermbg=NONE cterm=NONE
  hi Error ctermfg=124 ctermbg=230 cterm=bold,reverse
  hi Exception ctermfg=124 ctermbg=NONE cterm=NONE
  hi Float ctermfg=126 ctermbg=NONE cterm=NONE
  hi Function ctermfg=100 ctermbg=NONE
  hi Identifier ctermfg=23 ctermbg=NONE cterm=NONE
  hi Ignore ctermfg=fg ctermbg=NONE cterm=NONE
  hi Include ctermfg=29 ctermbg=NONE cterm=NONE
  hi Keyword ctermfg=124 ctermbg=NONE cterm=NONE
  hi Label ctermfg=124 ctermbg=NONE cterm=NONE
  hi Macro ctermfg=29 ctermbg=NONE cterm=NONE
  hi Number ctermfg=126 ctermbg=NONE cterm=NONE
  hi Operator ctermfg=29 ctermbg=NONE cterm=NONE
  hi PreCondit ctermfg=29 ctermbg=NONE cterm=NONE
  hi PreProc ctermfg=29 ctermbg=NONE cterm=NONE
  hi Repeat ctermfg=124 ctermbg=NONE cterm=NONE
  hi SpecialChar ctermfg=124 ctermbg=NONE cterm=NONE
  hi SpecialComment ctermfg=124 ctermbg=NONE cterm=NONE
  hi Statement ctermfg=124 ctermbg=NONE cterm=NONE
  hi StorageClass ctermfg=124 ctermbg=NONE cterm=NONE
  hi Special ctermfg=124 ctermbg=NONE cterm=italic
  hi String ctermfg=100 ctermbg=NONE cterm=italic
  hi Structure ctermfg=29 ctermbg=NONE cterm=NONE
  hi Todo ctermfg=fg ctermbg=230 cterm=bold,italic
  hi Type ctermfg=172 ctermbg=NONE cterm=NONE
  hi Typedef ctermfg=172 ctermbg=NONE cterm=NONE
  hi Underlined ctermfg=23 ctermbg=NONE cterm=underline
  hi CursorIM ctermfg=NONE ctermbg=NONE cterm=reverse
  if !s:italics
    hi Comment cterm=NONE
    hi Folded cterm=NONE
    hi SpellBad cterm=underline
    hi SpellCap cterm=underline
    hi SpellLocal cterm=underline
    hi SpellRare cterm=underline
    hi Special cterm=NONE
    hi String cterm=NONE
    hi Todo cterm=bold
  endif
  if !get(g:, 'gruvbox_italicize_strings', 1)
    hi Special gui=NONE cterm=NONE
    hi String gui=NONE cterm=NONE
  endif
  hi NormalMode ctermfg=243 ctermbg=230 cterm=reverse
  hi InsertMode ctermfg=23 ctermbg=230 cterm=reverse
  hi ReplaceMode ctermfg=29 ctermbg=230 cterm=reverse
  hi VisualMode ctermfg=124 ctermbg=230 cterm=reverse
  hi CommandMode ctermfg=126 ctermbg=230 cterm=reverse
  hi Warnings ctermfg=124 ctermbg=230 cterm=reverse
  if !(get(g:, 'gruvbox_plugin_hi_groups', 0) || get(g:, 'gruvbox_filetype_hi_groups', 0))
    finish
  endif
  if get(g:, "gruvbox_plugin_hi_groups", 0)
    hi ALEError ctermfg=NONE ctermbg=NONE cterm=underline
    hi ALEWarning ctermfg=NONE ctermbg=NONE cterm=underline
    hi ALEInfo ctermfg=NONE ctermbg=NONE cterm=underline
    hi ALEErrorSign ctermfg=124 ctermbg=187 cterm=NONE
    hi ALEWarningSign ctermfg=172 ctermbg=187 cterm=NONE
    hi ALEInfoSign ctermfg=23 ctermbg=187 cterm=NONE
    hi BufTabLineCurrent ctermfg=230 ctermbg=243 cterm=NONE
    hi BufTabLineActive ctermfg=243 ctermbg=187 cterm=NONE
    hi BufTabLineHidden ctermfg=137 ctermbg=187 cterm=NONE
    hi BufTabLineFill ctermfg=230 ctermbg=230 cterm=NONE
    hi CocErrorSign ctermfg=124 ctermbg=187 cterm=NONE
    hi CocWarningSign ctermfg=124 ctermbg=187 cterm=NONE
    hi CocInfoSign ctermfg=172 ctermbg=187 cterm=NONE
    hi CocHintSign ctermfg=23 ctermbg=187 cterm=NONE
    hi CocErrorFloat ctermfg=124 ctermbg=NONE cterm=NONE
    hi CocWarningFloat ctermfg=124 ctermbg=NONE cterm=NONE
    hi CocInfoFloat ctermfg=172 ctermbg=NONE cterm=NONE
    hi CocHintFloat ctermfg=23 ctermbg=NONE cterm=NONE
    hi CtrlPMatch ctermfg=172 ctermbg=NONE cterm=NONE
    hi CtrlPNoEntries ctermfg=124 ctermbg=NONE cterm=NONE
    hi CtrlPPrtBase ctermfg=187 ctermbg=NONE cterm=NONE
    hi CtrlPPrtCursor ctermfg=23 ctermbg=NONE cterm=NONE
    hi CtrlPLinePre ctermfg=187 ctermbg=NONE cterm=NONE
    hi CtrlPMode1 ctermfg=23 ctermbg=187 cterm=bold
    hi CtrlPMode2 ctermfg=230 ctermbg=23 cterm=bold
    hi CtrlPStats ctermfg=243 ctermbg=187 cterm=bold
    hi DirvishPathTail ctermfg=29 ctermbg=NONE cterm=NONE
    hi DirvishArg ctermfg=172 ctermbg=NONE cterm=NONE
    hi! link EasyMotionTarget Search
    hi! link EasyMotionShade Comment
    hi gitcommitSelectedFile ctermfg=100 ctermbg=NONE cterm=NONE
    hi gitcommitDiscardedFile ctermfg=124 ctermbg=NONE cterm=NONE
    if get(g:, 'gruvbox_transp_bg', 0)
      hi GitGutterAdd ctermfg=100 ctermbg=NONE cterm=NONE
      hi GitGutterChange ctermfg=29 ctermbg=NONE cterm=NONE
      hi GitGutterDelete ctermfg=124 ctermbg=NONE cterm=NONE
      hi GitGutterChangeDelete ctermfg=29 ctermbg=NONE cterm=NONE
    else
      hi GitGutterAdd ctermfg=100 ctermbg=187 cterm=NONE
      hi GitGutterChange ctermfg=29 ctermbg=187 cterm=NONE
      hi GitGutterDelete ctermfg=124 ctermbg=187 cterm=NONE
      hi GitGutterChangeDelete ctermfg=29 ctermbg=187 cterm=NONE
    endif
    if get(g:, 'indent_guides_auto_colors', 0)
      if get(g:, 'gruvbox_invert_indent_guides', 0)
        hi IndentGuidesOdd ctermfg=230 ctermbg=187 cterm=reverse
        hi IndentGuidesEven ctermfg=230 ctermbg=187 cterm=reverse
      else
        hi IndentGuidesOdd ctermfg=230 ctermbg=187 cterm=NONE
        hi IndentGuidesEven ctermfg=230 ctermbg=187 cterm=NONE
      endif
    endif
    if !exists('g:indentLine_color_term')
      let g:indentLine_color_term = 187
    endif
    if !exists('g:indentLine_color_gui')
      let g:indentLine_color_gui = '#d5c4a1'
    endif
    hi LspDiagnosticsDefaultError ctermfg=124 ctermbg=NONE cterm=NONE
    hi LspDiagnosticsSignError ctermfg=124 ctermbg=187 cterm=NONE
    hi LspDiagnosticsUnderlineError ctermfg=NONE ctermbg=NONE cterm=NONE
    hi LspDiagnosticsDefaultWarning ctermfg=124 ctermbg=NONE cterm=NONE
    hi LspDiagnosticsSignWarning ctermfg=124 ctermbg=187 cterm=NONE
    hi LspDiagnosticsUnderlineWarning ctermfg=NONE ctermbg=NONE cterm=NONE
    hi LspDiagnosticsDefaultInformation ctermfg=172 ctermbg=NONE cterm=NONE
    hi LspDiagnosticsSignInformation ctermfg=172 ctermbg=187 cterm=NONE
    hi LspDiagnosticsUnderlineInformation ctermfg=NONE ctermbg=NONE cterm=NONE
    hi LspDiagnosticsDefaultHint ctermfg=23 ctermbg=NONE cterm=NONE
    hi LspDiagnosticsSignHint ctermfg=23 ctermbg=187 cterm=NONE
    hi LspDiagnosticsUnderlineHint ctermfg=NONE ctermbg=NONE cterm=NONE
    hi LanguageClientError ctermfg=124 ctermbg=NONE cterm=NONE
    hi LanguageClientErrorSign ctermfg=124 ctermbg=230 cterm=NONE
    hi LanguageClientWarning ctermfg=172 ctermbg=NONE cterm=NONE
    hi LanguageClientWarningSign ctermfg=172 ctermbg=187 cterm=NONE
    hi LangaugeClientInfo ctermfg=23 ctermbg=NONE cterm=NONE
    hi LanguageClientInfoSign ctermfg=23 ctermbg=187 cterm=NONE
    hi LanguageClientCodeLens ctermfg=23 ctermbg=NONE cterm=NONE
    hi NERDTreeDir ctermfg=29 ctermbg=NONE cterm=NONE
    hi NERDTreeDirSlash ctermfg=29 ctermbg=NONE cterm=NONE
    hi NERDTreeOpenable ctermfg=124 ctermbg=NONE cterm=NONE
    hi NERDTreeClosable ctermfg=124 ctermbg=NONE cterm=NONE
    hi NERDTreeFile ctermfg=237 ctermbg=NONE cterm=NONE
    hi NERDTreeExecFile ctermfg=172 ctermbg=NONE cterm=NONE
    hi NERDTreeUp ctermfg=102 ctermbg=NONE cterm=NONE
    hi NERDTreeCWD ctermfg=100 ctermbg=NONE cterm=NONE
    hi NERDTreeHelp ctermfg=237 ctermbg=NONE cterm=NONE
    hi NERDTreeToggleOn ctermfg=100 ctermbg=NONE cterm=NONE
    hi NERDTreeToggleOff ctermfg=124 ctermbg=NONE cterm=NONE
    hi netrwDir ctermfg=29 ctermbg=NONE cterm=NONE
    hi netrwClassify ctermfg=29 ctermbg=NONE cterm=NONE
    hi netrwLink ctermfg=102 ctermbg=NONE cterm=NONE
    hi netrwSymLink ctermfg=237 ctermbg=NONE cterm=NONE
    hi netrwExe ctermfg=172 ctermbg=NONE cterm=NONE
    hi netrwComment ctermfg=102 ctermbg=NONE cterm=NONE
    hi netrwList ctermfg=23 ctermbg=NONE cterm=NONE
    hi netrwHelpCmd ctermfg=29 ctermbg=NONE cterm=NONE
    hi netrwCmdSep ctermfg=59 ctermbg=NONE cterm=NONE
    hi netrwVersion ctermfg=100 ctermbg=NONE cterm=NONE
    " Rainbow Parentheses
    if !exists('g:rbpt_colorpairs')
      let g:rbpt_colorpairs = [['blue', '#458588'], ['magenta', '#b16286'],
            \ ['red', '#cc241d'], ['166', '#d65d0e']]
    endif

    let g:rainbow_guifgs = [ '#d65d0e', '#cc241d', '#b16286', '#458588' ]
    let g:rainbow_ctermfgs = [ '166', 'red', 'magenta', 'blue' ]

    if !exists('g:rainbow_conf')
      let g:rainbow_conf = {}
    endif
    if !has_key(g:rainbow_conf, 'guifgs')
      let g:rainbow_conf['guifgs'] = g:rainbow_guifgs
    endif
    if !has_key(g:rainbow_conf, 'ctermfgs')
      let g:rainbow_conf['ctermfgs'] = g:rainbow_ctermfgs
    endif

    let g:niji_dark_colours = g:rbpt_colorpairs
    let g:niji_light_colours = g:rbpt_colorpairs
    hi ShowMarksHLl ctermfg=23 ctermbg=187 cterm=NONE
    hi ShowMarksHLu ctermfg=23 ctermbg=187 cterm=NONE
    hi ShowMarksHLo ctermfg=23 ctermbg=187 cterm=NONE
    hi ShowMarksHLm ctermfg=23 ctermbg=187 cterm=NONE
    hi SignifySignAdd ctermfg=100 ctermbg=187 cterm=NONE
    hi SignifySignChange ctermfg=29 ctermbg=187 cterm=NONE
    hi SignifySignDelete ctermfg=124 ctermbg=187 cterm=NONE
    hi SignatureMarkText ctermfg=23 ctermbg=187 cterm=NONE
    hi SignatureMarkerText ctermfg=126 ctermbg=187 cterm=NONE
    hi StartifyBracket ctermfg=59 ctermbg=NONE cterm=NONE
    hi StartifyFile ctermfg=237 ctermbg=NONE cterm=NONE
    hi StartifyNumber ctermfg=23 ctermbg=NONE cterm=NONE
    hi StartifyPath ctermfg=102 ctermbg=NONE cterm=NONE
    hi StartifySlash ctermfg=102 ctermbg=NONE cterm=NONE
    hi StartifySection ctermfg=172 ctermbg=NONE cterm=NONE
    hi StartifySpecial ctermfg=187 ctermbg=NONE cterm=NONE
    hi StartifyHeader ctermfg=124 ctermbg=NONE cterm=NONE
    hi StartifyFooter ctermfg=187 ctermbg=NONE cterm=NONE
    hi SyntasticError ctermfg=NONE ctermbg=NONE cterm=underline
    hi SyntasticWarning ctermfg=NONE ctermbg=NONE cterm=underline
    hi SyntasticErrorSign ctermfg=124 ctermbg=187 cterm=NONE
    hi SyntasticWarningSign ctermfg=172 ctermbg=187 cterm=NONE
    hi multiple_cursors_cursor ctermfg=NONE ctermbg=NONE cterm=reverse
    hi multiple_cursors_visual ctermfg=NONE ctermbg=187 cterm=NONE
    let g:vimshell_escape_colors = [
          \ '#a89984', '#9d0006', '#79740e', '#b57614',
          \ '#076678', '#8f3f71', '#427b58', '#7c6f64',
          \ '#fbf1c7', '#9d0006', '#79740e', '#af3a03',
          \ '#076678', '#8f3f71', '#427b58', '#282828'
          \ ]
  endif
  if get(g:, "gruvbox_filetype_hi_groups", 0)
    hi diffAdded ctermfg=100 ctermbg=NONE cterm=NONE
    hi diffRemoved ctermfg=124 ctermbg=NONE cterm=NONE
    hi diffChanged ctermfg=29 ctermbg=NONE cterm=NONE
    hi diffFile ctermfg=124 ctermbg=NONE cterm=NONE
    hi diffNewFile ctermfg=172 ctermbg=NONE cterm=NONE
    hi diffLine ctermfg=23 ctermbg=NONE cterm=NONE
    hi htmlTag ctermfg=23 ctermbg=NONE cterm=NONE
    hi htmlEndTag ctermfg=23 ctermbg=NONE cterm=NONE
    hi htmlTagName ctermfg=29 ctermbg=NONE cterm=bold
    hi htmlArg ctermfg=29 ctermbg=NONE cterm=NONE
    hi htmlScriptTag ctermfg=126 ctermbg=NONE cterm=NONE
    hi htmlTagN ctermfg=237 ctermbg=NONE cterm=NONE
    hi htmlSpecialTagName ctermfg=29 ctermbg=NONE cterm=bold
    hi htmlLink ctermfg=243 ctermbg=NONE cterm=underline
    hi htmlSpecialChar ctermfg=124 ctermbg=NONE cterm=NONE
    hi htmlBold ctermfg=fg ctermbg=230 cterm=bold
    hi htmlBoldUnderline ctermfg=fg ctermbg=230 cterm=bold,underline
    hi htmlBoldItalic ctermfg=fg ctermbg=230 cterm=bold,italic
    hi htmlBoldUnderlineItalic ctermfg=fg ctermbg=230 cterm=bold,italic,underline
    hi htmlUnderline ctermfg=fg ctermbg=230 cterm=underline
    hi htmlUnderlineItalic ctermfg=fg ctermbg=230 cterm=italic,underline
    hi htmlItalic ctermfg=fg ctermbg=230 cterm=italic
    hi xmlTag ctermfg=23 ctermbg=NONE cterm=NONE
    hi xmlEndTag ctermfg=23 ctermbg=NONE cterm=NONE
    hi xmlTagName ctermfg=23 ctermbg=NONE cterm=NONE
    hi xmlEqual ctermfg=23 ctermbg=NONE cterm=NONE
    hi docbkKeyword ctermfg=29 ctermbg=NONE cterm=bold
    hi xmlDocTypeDecl ctermfg=102 ctermbg=NONE cterm=NONE
    hi xmlDocTypeKeyword ctermfg=126 ctermbg=NONE cterm=NONE
    hi xmlCdataStart ctermfg=102 ctermbg=NONE cterm=NONE
    hi xmlCdataCdata ctermfg=126 ctermbg=NONE cterm=NONE
    hi dtdFunction ctermfg=102 ctermbg=NONE cterm=NONE
    hi dtdTagName ctermfg=126 ctermbg=NONE cterm=NONE
    hi xmlAttrib ctermfg=29 ctermbg=NONE cterm=NONE
    hi xmlProcessingDelim ctermfg=102 ctermbg=NONE cterm=NONE
    hi dtdParamEntityPunct ctermfg=102 ctermbg=NONE cterm=NONE
    hi dtdParamEntityDPunct ctermfg=102 ctermbg=NONE cterm=NONE
    hi xmlAttribPunct ctermfg=102 ctermbg=NONE cterm=NONE
    hi xmlEntity ctermfg=124 ctermbg=NONE cterm=NONE
    hi xmlEntityPunct ctermfg=124 ctermbg=NONE cterm=NONE
    hi vimCommentTitle ctermfg=243 ctermbg=NONE cterm=bold
    hi vimNotation ctermfg=124 ctermbg=NONE cterm=NONE
    hi vimBracket ctermfg=124 ctermbg=NONE cterm=NONE
    hi vimMapModKey ctermfg=124 ctermbg=NONE cterm=NONE
    hi vimFuncSID ctermfg=59 ctermbg=NONE cterm=NONE
    hi vimSetSep ctermfg=59 ctermbg=NONE cterm=NONE
    hi vimSep ctermfg=59 ctermbg=NONE cterm=NONE
    hi vimContinue ctermfg=59 ctermbg=NONE cterm=NONE
    hi clojureKeyword ctermfg=23 ctermbg=NONE cterm=NONE
    hi clojureCond ctermfg=124 ctermbg=NONE cterm=NONE
    hi clojureSpecial ctermfg=124 ctermbg=NONE cterm=NONE
    hi clojureDefine ctermfg=124 ctermbg=NONE cterm=NONE
    hi clojureFunc ctermfg=172 ctermbg=NONE cterm=NONE
    hi clojureRepeat ctermfg=172 ctermbg=NONE cterm=NONE
    hi clojureCharacter ctermfg=29 ctermbg=NONE cterm=NONE
    hi clojureStringEscape ctermfg=29 ctermbg=NONE cterm=NONE
    hi clojureException ctermfg=124 ctermbg=NONE cterm=NONE
    hi clojureRegexp ctermfg=29 ctermbg=NONE cterm=NONE
    hi clojureRegexpEscape ctermfg=29 ctermbg=NONE cterm=NONE
    hi clojureRegexpCharClass ctermfg=59 ctermbg=NONE cterm=bold
    hi! link clojureRegexpMod clojureRegexpCharClass
    hi! link clojureRegexpQuantifier clojureRegexpCharClass
    hi clojureParen ctermfg=59 ctermbg=NONE cterm=NONE
    hi clojureAnonArg ctermfg=172 ctermbg=NONE cterm=NONE
    hi clojureVariable ctermfg=23 ctermbg=NONE cterm=NONE
    hi clojureMacro ctermfg=124 ctermbg=NONE cterm=NONE
    hi clojureMeta ctermfg=172 ctermbg=NONE cterm=NONE
    hi clojureDeref ctermfg=172 ctermbg=NONE cterm=NONE
    hi clojureQuote ctermfg=172 ctermbg=NONE cterm=NONE
    hi clojureUnquote ctermfg=172 ctermbg=NONE cterm=NONE
    hi cOperator ctermfg=126 ctermbg=NONE cterm=NONE
    hi cStructure ctermfg=124 ctermbg=NONE cterm=NONE
    hi pythonBuiltin ctermfg=124 ctermbg=NONE cterm=NONE
    hi pythonBuiltinObj ctermfg=124 ctermbg=NONE cterm=NONE
    hi pythonBuiltinFunc ctermfg=124 ctermbg=NONE cterm=NONE
    hi pythonFunction ctermfg=29 ctermbg=NONE cterm=NONE
    hi pythonDecorator ctermfg=124 ctermbg=NONE cterm=NONE
    hi pythonInclude ctermfg=23 ctermbg=NONE cterm=NONE
    hi pythonImport ctermfg=23 ctermbg=NONE cterm=NONE
    hi pythonRun ctermfg=23 ctermbg=NONE cterm=NONE
    hi pythonCoding ctermfg=23 ctermbg=NONE cterm=NONE
    hi pythonOperator ctermfg=124 ctermbg=NONE cterm=NONE
    hi pythonException ctermfg=124 ctermbg=NONE cterm=NONE
    hi pythonExceptions ctermfg=126 ctermbg=NONE cterm=NONE
    hi pythonBoolean ctermfg=126 ctermbg=NONE cterm=NONE
    hi pythonDot ctermfg=59 ctermbg=NONE cterm=NONE
    hi pythonConditional ctermfg=124 ctermbg=NONE cterm=NONE
    hi pythonRepeat ctermfg=124 ctermbg=NONE cterm=NONE
    hi pythonDottedName ctermfg=100 ctermbg=NONE cterm=bold
    hi cssBraces ctermfg=23 ctermbg=NONE cterm=NONE
    hi cssFunctionName ctermfg=172 ctermbg=NONE cterm=NONE
    hi cssIdentifier ctermfg=124 ctermbg=NONE cterm=NONE
    hi cssClassName ctermfg=100 ctermbg=NONE cterm=NONE
    hi cssColor ctermfg=23 ctermbg=NONE cterm=NONE
    hi cssSelectorOp ctermfg=23 ctermbg=NONE cterm=NONE
    hi cssSelectorOp2 ctermfg=23 ctermbg=NONE cterm=NONE
    hi cssImportant ctermfg=100 ctermbg=NONE cterm=NONE
    hi cssVendor ctermfg=237 ctermbg=NONE cterm=NONE
    hi cssTextProp ctermfg=29 ctermbg=NONE cterm=NONE
    hi cssAnimationProp ctermfg=29 ctermbg=NONE cterm=NONE
    hi cssUIProp ctermfg=172 ctermbg=NONE cterm=NONE
    hi cssTransformProp ctermfg=29 ctermbg=NONE cterm=NONE
    hi cssTransitionProp ctermfg=29 ctermbg=NONE cterm=NONE
    hi cssPrintProp ctermfg=29 ctermbg=NONE cterm=NONE
    hi cssPositioningProp ctermfg=172 ctermbg=NONE cterm=NONE
    hi cssBoxProp ctermfg=29 ctermbg=NONE cterm=NONE
    hi cssFontDescriptorProp ctermfg=29 ctermbg=NONE cterm=NONE
    hi cssFlexibleBoxProp ctermfg=29 ctermbg=NONE cterm=NONE
    hi cssBorderOutlineProp ctermfg=29 ctermbg=NONE cterm=NONE
    hi cssBackgroundProp ctermfg=29 ctermbg=NONE cterm=NONE
    hi cssMarginProp ctermfg=29 ctermbg=NONE cterm=NONE
    hi cssListProp ctermfg=29 ctermbg=NONE cterm=NONE
    hi cssTableProp ctermfg=29 ctermbg=NONE cterm=NONE
    hi cssFontProp ctermfg=29 ctermbg=NONE cterm=NONE
    hi cssPaddingProp ctermfg=29 ctermbg=NONE cterm=NONE
    hi cssDimensionProp ctermfg=29 ctermbg=NONE cterm=NONE
    hi cssRenderProp ctermfg=29 ctermbg=NONE cterm=NONE
    hi cssColorProp ctermfg=29 ctermbg=NONE cterm=NONE
    hi cssGeneratedContentProp ctermfg=29 ctermbg=NONE cterm=NONE
    hi javaScriptBraces ctermfg=237 ctermbg=NONE cterm=NONE
    hi javaScriptFunction ctermfg=29 ctermbg=NONE cterm=NONE
    hi javaScriptIdentifier ctermfg=124 ctermbg=NONE cterm=NONE
    hi javaScriptMember ctermfg=23 ctermbg=NONE cterm=NONE
    hi javaScriptNumber ctermfg=126 ctermbg=NONE cterm=NONE
    hi javaScriptNull ctermfg=126 ctermbg=NONE cterm=NONE
    hi javaScriptParens ctermfg=59 ctermbg=NONE cterm=NONE
    hi javascriptImport ctermfg=29 ctermbg=NONE cterm=NONE
    hi javascriptExport ctermfg=29 ctermbg=NONE cterm=NONE
    hi javascriptClassKeyword ctermfg=29 ctermbg=NONE cterm=NONE
    hi javascriptClassExtends ctermfg=29 ctermbg=NONE cterm=NONE
    hi javascriptDefault ctermfg=29 ctermbg=NONE cterm=NONE
    hi javascriptClassName ctermfg=172 ctermbg=NONE cterm=NONE
    hi javascriptClassSuperName ctermfg=172 ctermbg=NONE cterm=NONE
    hi javascriptGlobal ctermfg=172 ctermbg=NONE cterm=NONE
    hi javascriptEndColons ctermfg=237 ctermbg=NONE cterm=NONE
    hi javascriptFuncArg ctermfg=237 ctermbg=NONE cterm=NONE
    hi javascriptGlobalMethod ctermfg=237 ctermbg=NONE cterm=NONE
    hi javascriptNodeGlobal ctermfg=237 ctermbg=NONE cterm=NONE
    hi javascriptBOMWindowProp ctermfg=237 ctermbg=NONE cterm=NONE
    hi javascriptArrayMethod ctermfg=237 ctermbg=NONE cterm=NONE
    hi javascriptArrayStaticMethod ctermfg=237 ctermbg=NONE cterm=NONE
    hi javascriptCacheMethod ctermfg=237 ctermbg=NONE cterm=NONE
    hi javascriptDateMethod ctermfg=237 ctermbg=NONE cterm=NONE
    hi javascriptMathStaticMethod ctermfg=237 ctermbg=NONE cterm=NONE
    hi javascriptURLUtilsProp ctermfg=237 ctermbg=NONE cterm=NONE
    hi javascriptBOMNavigatorProp ctermfg=237 ctermbg=NONE cterm=NONE
    hi javascriptDOMDocMethod ctermfg=237 ctermbg=NONE cterm=NONE
    hi javascriptDOMDocProp ctermfg=237 ctermbg=NONE cterm=NONE
    hi javascriptBOMLocationMethod ctermfg=237 ctermbg=NONE cterm=NONE
    hi javascriptBOMWindowMethod ctermfg=237 ctermbg=NONE cterm=NONE
    hi javascriptStringMethod ctermfg=237 ctermbg=NONE cterm=NONE
    hi javascriptVariable ctermfg=124 ctermbg=NONE cterm=NONE
    hi javascriptIdentifier ctermfg=124 ctermbg=NONE cterm=NONE
    hi javascriptClassSuper ctermfg=124 ctermbg=NONE cterm=NONE
    hi javascriptFuncKeyword ctermfg=29 ctermbg=NONE cterm=NONE
    hi javascriptAsyncFunc ctermfg=29 ctermbg=NONE cterm=NONE
    hi javascriptClassStatic ctermfg=124 ctermbg=NONE cterm=NONE
    hi javascriptOperator ctermfg=124 ctermbg=NONE cterm=NONE
    hi javascriptForOperator ctermfg=124 ctermbg=NONE cterm=NONE
    hi javascriptYield ctermfg=124 ctermbg=NONE cterm=NONE
    hi javascriptExceptions ctermfg=124 ctermbg=NONE cterm=NONE
    hi javascriptMessage ctermfg=124 ctermbg=NONE cterm=NONE
    hi javascriptTemplateSB ctermfg=29 ctermbg=NONE cterm=NONE
    hi javascriptTemplateSubstitution ctermfg=237 ctermbg=NONE cterm=NONE
    hi javascriptLabel ctermfg=237 ctermbg=NONE cterm=NONE
    hi javascriptObjectLabel ctermfg=237 ctermbg=NONE cterm=NONE
    hi javascriptPropertyName ctermfg=237 ctermbg=NONE cterm=NONE
    hi javascriptLogicSymbols ctermfg=237 ctermbg=NONE cterm=NONE
    hi javascriptArrowFunc ctermfg=172 ctermbg=NONE cterm=NONE
    hi javascriptDocParamName ctermfg=243 ctermbg=NONE cterm=NONE
    hi javascriptDocTags ctermfg=243 ctermbg=NONE cterm=NONE
    hi javascriptDocNotation ctermfg=243 ctermbg=NONE cterm=NONE
    hi javascriptDocParamType ctermfg=243 ctermbg=NONE cterm=NONE
    hi javascriptDocNamedParamType ctermfg=243 ctermbg=NONE cterm=NONE
    hi javascriptBrackets ctermfg=237 ctermbg=NONE cterm=NONE
    hi javascriptDOMElemAttrs ctermfg=237 ctermbg=NONE cterm=NONE
    hi javascriptDOMEventMethod ctermfg=237 ctermbg=NONE cterm=NONE
    hi javascriptDOMNodeMethod ctermfg=237 ctermbg=NONE cterm=NONE
    hi javascriptDOMStorageMethod ctermfg=237 ctermbg=NONE cterm=NONE
    hi javascriptHeadersMethod ctermfg=237 ctermbg=NONE cterm=NONE
    hi javascriptAsyncFuncKeyword ctermfg=124 ctermbg=NONE cterm=NONE
    hi javascriptAwaitFuncKeyword ctermfg=124 ctermbg=NONE cterm=NONE
    hi jsImport ctermfg=124 ctermbg=NONE cterm=NONE
    hi jsExport ctermfg=124 ctermbg=NONE cterm=NONE
    hi jsFrom ctermfg=124 ctermbg=NONE cterm=NONE
    hi jsThis ctermfg=126 ctermbg=NONE cterm=NONE
    hi jsParen ctermfg=23 ctermbg=NONE cterm=NONE
    hi jsOperator ctermfg=29 ctermbg=NONE cterm=NONE
    hi jsSpreadOperator ctermfg=100 ctermbg=NONE cterm=NONE
    hi jsSpreadExpression ctermfg=23 ctermbg=NONE cterm=NONE
    hi jsClassKeyword ctermfg=124 ctermbg=NONE cterm=NONE
    hi jsClassProperty ctermfg=100 ctermbg=NONE cterm=NONE
    hi jsExtendsKeyword ctermfg=124 ctermbg=NONE cterm=NONE
    hi jsExportDefault ctermfg=124 ctermbg=NONE cterm=bold
    hi jsTemplateBraces ctermfg=29 ctermbg=NONE cterm=NONE
    hi jsGlobalNodeObjects ctermfg=237 ctermbg=NONE cterm=NONE
    hi jsGlobalObjects ctermfg=237 ctermbg=NONE cterm=NONE
    hi jsFunction ctermfg=100 ctermbg=NONE cterm=NONE
    hi jsFuncParens ctermfg=126 ctermbg=NONE cterm=NONE
    hi jsFuncBlock ctermfg=23 ctermbg=NONE cterm=NONE
    hi jsParens ctermfg=59 ctermbg=NONE cterm=NONE
    hi jsNull ctermfg=126 ctermbg=NONE cterm=NONE
    hi jsUndefined ctermfg=126 ctermbg=NONE cterm=NONE
    hi jsClassDefinition ctermfg=172 ctermbg=NONE cterm=NONE
    hi jsFunctionKey ctermfg=100 ctermbg=NONE cterm=NONE
    hi jsBracket ctermfg=124 ctermbg=NONE cterm=NONE
    hi jsObjectColon ctermfg=124 ctermbg=NONE cterm=NONE
    hi jsObjectProp ctermfg=23 ctermbg=NONE cterm=NONE
    hi jsFuncBraces ctermfg=100 ctermbg=NONE cterm=NONE
    hi jsVariableDef ctermfg=172 ctermbg=NONE cterm=NONE
    hi jsObjectValue ctermfg=23 ctermbg=NONE cterm=NONE
    hi jsDestructuringBlock ctermfg=172 ctermbg=NONE cterm=NONE
    hi jsParenIfElse ctermfg=23 ctermbg=NONE cterm=NONE
    hi jsClassBlock ctermfg=23 ctermbg=NONE cterm=NONE
    hi jsFutureKeys ctermfg=124 ctermbg=NONE cterm=bold
    hi jsStorageClass ctermfg=124 ctermbg=NONE cterm=NONE
    hi jsModuleKeyword ctermfg=23 ctermbg=NONE cterm=NONE
    hi jsObjectShorthandProp ctermfg=23 ctermbg=NONE cterm=NONE
    hi jsxRegion ctermfg=23 ctermbg=NONE cterm=NONE
    hi jsxTagName ctermfg=23 ctermbg=NONE cterm=NONE
    hi jsxComponentName ctermfg=172 ctermbg=NONE cterm=NONE
    hi jsxEscapeJsAttributes ctermfg=23 ctermbg=NONE cterm=NONE
    hi jsxEscapeJsContent ctermfg=23 ctermbg=NONE cterm=NONE
    hi jsxAttrib ctermfg=172 ctermbg=NONE cterm=NONE
    hi jsxAttributeBraces ctermfg=237 ctermbg=NONE cterm=NONE
    hi jsxEqual ctermfg=29 ctermbg=NONE cterm=NONE
    hi jsxString ctermfg=100 ctermbg=NONE cterm=NONE
    hi jsxCloseTag ctermfg=23 ctermbg=NONE cterm=NONE
    hi jsxEndTag ctermfg=23 ctermbg=NONE cterm=NONE
    hi jsxEndString ctermfg=23 ctermbg=NONE cterm=NONE
    hi jsxCloseString ctermfg=23 ctermbg=NONE cterm=NONE
    hi jsxIfOperator ctermfg=29 ctermbg=NONE cterm=NONE
    hi jsxElseOperator ctermfg=29 ctermbg=NONE cterm=NONE
    hi jsxDot ctermfg=237 ctermbg=NONE cterm=NONE
    hi jsxNamespace ctermfg=23 ctermbg=NONE cterm=NONE
    hi jsxPunct ctermfg=29 ctermbg=NONE cterm=NONE
    hi typeScriptReserved ctermfg=29 ctermbg=NONE cterm=NONE
    hi typeScriptLabel ctermfg=29 ctermbg=NONE cterm=NONE
    hi typeScriptFuncKeyword ctermfg=29 ctermbg=NONE cterm=NONE
    hi typeScriptIdentifier ctermfg=124 ctermbg=NONE cterm=NONE
    hi typeScriptBraces ctermfg=237 ctermbg=NONE cterm=NONE
    hi typeScriptEndColons ctermfg=237 ctermbg=NONE cterm=NONE
    hi typeScriptDOMObjects ctermfg=237 ctermbg=NONE cterm=NONE
    hi typeScriptAjaxMethods ctermfg=237 ctermbg=NONE cterm=NONE
    hi typeScriptLogicSymbols ctermfg=237 ctermbg=NONE cterm=NONE
    hi! link typeScriptDocSeeTag Comment
    hi! link typeScriptDocParam Comment
    hi! link typeScriptDocTags vimCommentTitle
    hi typeScriptGlobalObjects ctermfg=237 ctermbg=NONE cterm=NONE
    hi typeScriptParens ctermfg=59 ctermbg=NONE cterm=NONE
    hi typeScriptOpSymbols ctermfg=59 ctermbg=NONE cterm=NONE
    hi typeScriptHtmlElemProperties ctermfg=237 ctermbg=NONE cterm=NONE
    hi typeScriptNull ctermfg=126 ctermbg=NONE cterm=NONE
    hi typeScriptInterpolationDelimiter ctermfg=29 ctermbg=NONE cterm=NONE
    hi purescriptModuleKeyword ctermfg=29 ctermbg=NONE cterm=NONE
    hi purescriptModuleName ctermfg=237 ctermbg=NONE cterm=NONE
    hi purescriptWhere ctermfg=29 ctermbg=NONE cterm=NONE
    hi purescriptDelimiter ctermfg=243 ctermbg=NONE cterm=NONE
    hi purescriptType ctermfg=237 ctermbg=NONE cterm=NONE
    hi purescriptImportKeyword ctermfg=29 ctermbg=NONE cterm=NONE
    hi purescriptHidingKeyword ctermfg=29 ctermbg=NONE cterm=NONE
    hi purescriptAsKeyword ctermfg=29 ctermbg=NONE cterm=NONE
    hi purescriptStructure ctermfg=29 ctermbg=NONE cterm=NONE
    hi purescriptOperator ctermfg=23 ctermbg=NONE cterm=NONE
    hi purescriptTypeVar ctermfg=237 ctermbg=NONE cterm=NONE
    hi purescriptConstructor ctermfg=237 ctermbg=NONE cterm=NONE
    hi purescriptFunction ctermfg=237 ctermbg=NONE cterm=NONE
    hi purescriptConditional ctermfg=124 ctermbg=NONE cterm=NONE
    hi purescriptBacktick ctermfg=124 ctermbg=NONE cterm=NONE
    hi coffeeExtendedOp ctermfg=59 ctermbg=NONE cterm=NONE
    hi coffeeSpecialOp ctermfg=59 ctermbg=NONE cterm=NONE
    hi coffeeCurly ctermfg=124 ctermbg=NONE cterm=NONE
    hi coffeeParen ctermfg=59 ctermbg=NONE cterm=NONE
    hi coffeeBracket ctermfg=124 ctermbg=NONE cterm=NONE
    hi rubyStringDelimiter ctermfg=100 ctermbg=NONE cterm=NONE
    hi rubyInterpolationDelimiter ctermfg=29 ctermbg=NONE cterm=NONE
    hi objcTypeModifier ctermfg=124 ctermbg=NONE cterm=NONE
    hi objcDirective ctermfg=23 ctermbg=NONE cterm=NONE
    hi goDirective ctermfg=29 ctermbg=NONE cterm=NONE
    hi goConstants ctermfg=126 ctermbg=NONE cterm=NONE
    hi goDeclaration ctermfg=124 ctermbg=NONE cterm=NONE
    hi goDeclType ctermfg=23 ctermbg=NONE cterm=NONE
    hi goBuiltins ctermfg=124 ctermbg=NONE cterm=NONE
    hi luaIn ctermfg=124 ctermbg=NONE cterm=NONE
    hi luaFunction ctermfg=29 ctermbg=NONE cterm=NONE
    hi luaTable ctermfg=124 ctermbg=NONE cterm=NONE
    hi moonSpecialOp ctermfg=59 ctermbg=NONE cterm=NONE
    hi moonExtendedOp ctermfg=59 ctermbg=NONE cterm=NONE
    hi moonFunction ctermfg=59 ctermbg=NONE cterm=NONE
    hi moonObject ctermfg=172 ctermbg=NONE cterm=NONE
    hi javaAnnotation ctermfg=23 ctermbg=NONE cterm=NONE
    hi javaDocTags ctermfg=29 ctermbg=NONE cterm=NONE
    hi! link javaCommentTitle vimCommentTitle
    hi javaParen ctermfg=59 ctermbg=NONE cterm=NONE
    hi javaParen1 ctermfg=59 ctermbg=NONE cterm=NONE
    hi javaParen2 ctermfg=59 ctermbg=NONE cterm=NONE
    hi javaParen3 ctermfg=59 ctermbg=NONE cterm=NONE
    hi javaParen4 ctermfg=59 ctermbg=NONE cterm=NONE
    hi javaParen5 ctermfg=59 ctermbg=NONE cterm=NONE
    hi javaOperator ctermfg=124 ctermbg=NONE cterm=NONE
    hi javaVarArg ctermfg=100 ctermbg=NONE cterm=NONE
    hi! link elixirDocString Comment
    hi elixirStringDelimiter ctermfg=100 ctermbg=NONE cterm=NONE
    hi elixirInterpolationDelimiter ctermfg=29 ctermbg=NONE cterm=NONE
    hi elixirModuleDeclaration ctermfg=172 ctermbg=NONE cterm=NONE
    hi scalaNameDefinition ctermfg=237 ctermbg=NONE cterm=NONE
    hi scalaCaseFollowing ctermfg=237 ctermbg=NONE cterm=NONE
    hi scalaCapitalWord ctermfg=237 ctermbg=NONE cterm=NONE
    hi scalaTypeExtension ctermfg=237 ctermbg=NONE cterm=NONE
    hi scalaKeyword ctermfg=124 ctermbg=NONE cterm=NONE
    hi scalaKeywordModifier ctermfg=124 ctermbg=NONE cterm=NONE
    hi scalaSpecial ctermfg=29 ctermbg=NONE cterm=NONE
    hi scalaOperator ctermfg=237 ctermbg=NONE cterm=NONE
    hi scalaTypeDeclaration ctermfg=172 ctermbg=NONE cterm=NONE
    hi scalaTypeTypePostDeclaration ctermfg=172 ctermbg=NONE cterm=NONE
    hi scalaInstanceDeclaration ctermfg=237 ctermbg=NONE cterm=NONE
    hi scalaInterpolation ctermfg=29 ctermbg=NONE cterm=NONE
    hi markdownItalic ctermfg=59 ctermbg=NONE cterm=italic
    hi markdownH1 ctermfg=100 ctermbg=NONE cterm=bold
    hi markdownH2 ctermfg=100 ctermbg=NONE cterm=bold
    hi markdownH3 ctermfg=172 ctermbg=NONE cterm=bold
    hi markdownH4 ctermfg=172 ctermbg=NONE cterm=bold
    hi markdownH5 ctermfg=172 ctermbg=NONE cterm=NONE
    hi markdownH6 ctermfg=172 ctermbg=NONE cterm=NONE
    hi markdownCode ctermfg=29 ctermbg=NONE cterm=NONE
    hi markdownCodeBlock ctermfg=29 ctermbg=NONE cterm=NONE
    hi markdownCodeDelimiter ctermfg=29 ctermbg=NONE cterm=NONE
    hi markdownBlockquote ctermfg=102 ctermbg=NONE cterm=NONE
    hi markdownListMarker ctermfg=102 ctermbg=NONE cterm=NONE
    hi markdownOrderedListMarker ctermfg=102 ctermbg=NONE cterm=NONE
    hi markdownRule ctermfg=102 ctermbg=NONE cterm=NONE
    hi markdownHeadingRule ctermfg=102 ctermbg=NONE cterm=NONE
    hi markdownUrlDelimiter ctermfg=59 ctermbg=NONE cterm=NONE
    hi markdownLinkDelimiter ctermfg=59 ctermbg=NONE cterm=NONE
    hi markdownLinkTextDelimiter ctermfg=59 ctermbg=NONE cterm=NONE
    hi markdownHeadingDelimiter ctermfg=124 ctermbg=NONE cterm=NONE
    hi markdownUrl ctermfg=126 ctermbg=NONE cterm=NONE
    hi markdownUrlTitleDelimiter ctermfg=100 ctermbg=NONE cterm=NONE
    hi markdownLinkText ctermfg=102 ctermbg=NONE cterm=underline
    hi! link markdownIdDeclaration markdownLinkText
    hi haskellType ctermfg=237 ctermbg=NONE cterm=NONE
    hi haskellIdentifier ctermfg=237 ctermbg=NONE cterm=NONE
    hi haskellSeparator ctermfg=237 ctermbg=NONE cterm=NONE
    hi haskellDelimiter ctermfg=243 ctermbg=NONE cterm=NONE
    hi haskellOperators ctermfg=23 ctermbg=NONE cterm=NONE
    hi haskellBacktick ctermfg=124 ctermbg=NONE cterm=NONE
    hi haskellStatement ctermfg=124 ctermbg=NONE cterm=NONE
    hi haskellConditional ctermfg=124 ctermbg=NONE cterm=NONE
    hi haskellLet ctermfg=29 ctermbg=NONE cterm=NONE
    hi haskellDefault ctermfg=29 ctermbg=NONE cterm=NONE
    hi haskellWhere ctermfg=29 ctermbg=NONE cterm=NONE
    hi haskellBottom ctermfg=29 ctermbg=NONE cterm=NONE
    hi haskellBlockKeywords ctermfg=29 ctermbg=NONE cterm=NONE
    hi haskellImportKeywords ctermfg=29 ctermbg=NONE cterm=NONE
    hi haskellDeclKeyword ctermfg=29 ctermbg=NONE cterm=NONE
    hi haskellDeriving ctermfg=29 ctermbg=NONE cterm=NONE
    hi haskellAssocType ctermfg=29 ctermbg=NONE cterm=NONE
    hi haskellNumber ctermfg=126 ctermbg=NONE cterm=NONE
    hi haskellPragma ctermfg=126 ctermbg=NONE cterm=NONE
    hi haskellString ctermfg=100 ctermbg=NONE cterm=NONE
    hi haskellChar ctermfg=100 ctermbg=NONE cterm=NONE
    hi jsonKeyword ctermfg=100 ctermbg=NONE cterm=NONE
    hi jsonQuote ctermfg=100 ctermbg=NONE cterm=NONE
    hi jsonBraces ctermfg=237 ctermbg=NONE cterm=NONE
    hi jsonString ctermfg=237 ctermbg=NONE cterm=NONE
    if !s:italics
      hi htmlBoldItalic cterm=bold
      hi htmlBoldUnderlineItalic cterm=bold,underline
      hi htmlUnderlineItalic cterm=underline
      hi htmlItalic cterm=NONE
      hi markdownItalic cterm=NONE
    endif
  endif
  unlet s:t_Co s:italics
  finish
endif

" Color: neutralred        rgb(204,  36,  29)    160 DarkRed
" Color: neutralgreen      rgb(152, 151,  26)    100 DarkGreen
" Color: neutralyellow     rgb(215, 153,  33)    172 DarkYellow
" Color: neutralblue       rgb( 69, 133, 136)    66  DarkBlue
" Color: neutralpurple     rgb(177,  98, 134)    132 DarkMagenta
" Color: neutralaqua       rgb(104, 157, 106)    71  DarkCyan
" Color: neutralorange     rgb(214,  93,  14)    166
" Background: dark
" Color: bg0 rgb(40,40,40) 235 Black
" Color: bg1             rgb(60,  56,  54)     237 DarkGray
" Color: bg2             rgb(80,  73,  69)     239
" Color: bg3             rgb(102, 92,  84)      59
" Color: bg4             rgb(124, 111, 100)    243
" Color: fg0             rgb(251, 241, 199)    230
" Color: fg1             rgb(235, 219, 178)    187 White
" Color: fg2             rgb(213, 196, 161)    187
" Color: fg3             rgb(189, 174, 147)    144
" Color: fg4             rgb(168, 153, 132)    137 Gray
" Color: grey            rgb(146, 131, 116)    102 DarkGray
" Color: red             rgb(251, 73,  52)     203 Red
" Color: green           rgb(184, 187, 38)     142 Green
" Color: yellow          rgb(250, 189, 47)     214 Yellow
" Color: blue            rgb(131, 165, 152)    109 Blue
" Color: purple          rgb(211, 134, 155)    175 Magenta
" Color: aqua            rgb(142, 192, 124)    107 Cyan
" Color: orange          rgb(254, 128, 25)     208 Magenta
" Term colors: bg0  neutralred neutralgreen neutralyellow neutralblue neutralpurple neutralaqua fg4
" Term colors: grey red        green        yellow        blue        purple        aqua        fg1
" Background: light
" Color: bg0 rgb(251, 241, 199) 230 White
" Color: bg1 rgb(235, 219, 178) 187 Grey
" Color: bg2 rgb(213, 196, 161) 187
" Color: bg3               rgb(189, 174, 147)    144
" Color: bg4               rgb(168, 153, 132)    137
" Color: fg0               rgb( 40,  40,  40)    235 DarkGray
" Color: fg1               rgb( 60,  56,  54)    237 Black
" Color: fg2               rgb( 80,  56,  54)    237
" Color: fg3               rgb(102,  92,  84)     59
" Color: fg4               rgb(124, 111, 100)    243 Black
" Color: grey              rgb(146, 131, 116)    102 DarkGray
" Color: red               rgb(157,   0,   6)    124 Red
" Color: green             rgb(121, 116,  14)    100 Green
" Color: yellow            rgb(181, 118,  20)    172 Yellow
" Color: blue              rgb(  7, 102, 120)    23  Blue
" Color: purple            rgb(143,  63, 113)    126 Magenta
" Color: aqua              rgb( 66, 123,  88)    29  Cyan
" Color: orange            rgb(175,  58,   3)    124 Magenta
" Term colors: fg1  neutralred neutralgreen neutralyellow neutralblue neutralpurple neutralaqua fg4
" Term colors: grey red        green        yellow        blue        purple        aqua        bg0
" Background: any
" vim: et ts=2 sw=2
